#define TENSOR_DISPATCH_NO_MAIN
#include "tensor_kernel_dispatch_spike.h"
#undef TENSOR_DISPATCH_NO_MAIN
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <mach/mach_time.h>
enum{TOKENS=7,MODEL=8,HEADS=2,HDIM=4,FFDIM=16};
enum Kind{K_QKV,K_VIEW,K_ATTENTION,K_CONTIGUOUS,K_OUTPROJ,K_RESIDUAL1,K_LAYERNORM1,K_FF1,K_RELU,K_FF2,K_RESIDUAL2,K_LAYERNORM2};
typedef struct{int(*run)(void*);void*context;uint32_t kind,flags;uint64_t reserved;}ExecStep;
typedef struct{Dispatch*d;uint32_t generation;float x[TOKENS*MODEL],wq[MODEL*3*MODEL],qkv[TOKENS*3*MODEL],score[HEADS*TOKENS*TOKENS],prob[HEADS*TOKENS*TOKENS],head[HEADS*TOKENS*HDIM],merged[TOKENS*MODEL],wo[MODEL*MODEL],proj[TOKENS*MODEL],sum1[TOKENS*MODEL],ln1[TOKENS*MODEL],mean1[TOKENS],inv1[TOKENS],w1[MODEL*FFDIM],ff1[TOKENS*FFDIM],act[TOKENS*FFDIM],w2[FFDIM*MODEL],ff2[TOKENS*MODEL],sum2[TOKENS*MODEL],out[TOKENS*MODEL],mean2[TOKENS],inv2[TOKENS];}Block;
typedef struct{Block*b;uint32_t expected_generation,kind,view_index;}Context;
#if defined(__aarch64__)
static int tensor_transformer_steps_execute(const ExecStep*s,uint64_t count){for(uint64_t i=0;i<count;i++){int rc=s[i].run(s[i].context);if(rc)return rc;}return 0;}
#else
extern int tensor_transformer_steps_execute(const ExecStep*,uint64_t);
#endif
static void norm(const float*x,float*y,float*mean,float*inv){for(int i=0;i<TOKENS;i++){float m=0,z=0;for(int j=0;j<MODEL;j++)m+=x[i*MODEL+j];m/=MODEL;for(int j=0;j<MODEL;j++){float q=x[i*MODEL+j]-m;z+=q*q;}mean[i]=m;inv[i]=1/sqrtf(z/MODEL+1e-5f);for(int j=0;j<MODEL;j++)y[i*MODEL+j]=(x[i*MODEL+j]-m)*inv[i];}}
static int run(void*opaque){Context*c=opaque;Block*b=c->b;if(c->expected_generation!=b->generation)return-4;switch(c->kind){case K_QKV:b->d->matmul(b->x,b->wq,b->qkv,TOKENS,MODEL,3*MODEL);break;case K_VIEW:if(c->view_index>2)return-1;break;case K_ATTENTION:{float scale=1/sqrtf(HDIM);for(int h=0;h<HEADS;h++)for(int i=0;i<TOKENS;i++){float mx=-INFINITY;for(int j=0;j<TOKENS;j++){float s=0;for(int d=0;d<HDIM;d++)s+=b->qkv[i*3*MODEL+h*HDIM+d]*b->qkv[j*3*MODEL+MODEL+h*HDIM+d];s*=scale;b->score[(h*TOKENS+i)*TOKENS+j]=s;mx=fmaxf(mx,s);}float total=0;for(int j=0;j<TOKENS;j++){float e=expf(b->score[(h*TOKENS+i)*TOKENS+j]-mx);b->prob[(h*TOKENS+i)*TOKENS+j]=e;total+=e;}for(int j=0;j<TOKENS;j++)b->prob[(h*TOKENS+i)*TOKENS+j]/=total;for(int d=0;d<HDIM;d++){float s=0;for(int j=0;j<TOKENS;j++)s+=b->prob[(h*TOKENS+i)*TOKENS+j]*b->qkv[j*3*MODEL+2*MODEL+h*HDIM+d];b->head[(h*TOKENS+i)*HDIM+d]=s;}}break;}case K_CONTIGUOUS:for(int i=0;i<TOKENS;i++)for(int h=0;h<HEADS;h++)for(int d=0;d<HDIM;d++)b->merged[i*MODEL+h*HDIM+d]=b->head[(h*TOKENS+i)*HDIM+d];break;case K_OUTPROJ:b->d->matmul(b->merged,b->wo,b->proj,TOKENS,MODEL,MODEL);break;case K_RESIDUAL1:b->d->residual(b->x,b->proj,b->sum1,TOKENS*MODEL);break;case K_LAYERNORM1:norm(b->sum1,b->ln1,b->mean1,b->inv1);break;case K_FF1:b->d->matmul(b->ln1,b->w1,b->ff1,TOKENS,MODEL,FFDIM);break;case K_RELU:b->d->relu(b->ff1,b->act,TOKENS*FFDIM);break;case K_FF2:b->d->matmul(b->act,b->w2,b->ff2,TOKENS,FFDIM,MODEL);break;case K_RESIDUAL2:b->d->residual(b->ln1,b->ff2,b->sum2,TOKENS*MODEL);break;case K_LAYERNORM2:norm(b->sum2,b->out,b->mean2,b->inv2);break;default:return-1;}return 0;}
static unsigned emit(Block*b,ExecStep*steps,Context*ctx){static const uint8_t kinds[]={K_QKV,K_VIEW,K_VIEW,K_VIEW,K_ATTENTION,K_CONTIGUOUS,K_OUTPROJ,K_RESIDUAL1,K_LAYERNORM1,K_FF1,K_RELU,K_FF2,K_RESIDUAL2,K_LAYERNORM2};for(unsigned i=0;i<14;i++){ctx[i]=(Context){b,b->generation,kinds[i],i>0&&i<4?i-1:0};steps[i]=(ExecStep){run,&ctx[i],kinds[i],0,0};}return 14;}
static void initialize(Block*b,Dispatch*d){memset(b,0,sizeof *b);b->d=d;b->generation=9;for(int i=0;i<TOKENS*MODEL;i++)b->x[i]=v(i,11);for(int i=0;i<MODEL*3*MODEL;i++)b->wq[i]=v(i,12)*.25f;for(int i=0;i<MODEL*MODEL;i++)b->wo[i]=v(i,13)*.25f;for(int i=0;i<MODEL*FFDIM;i++)b->w1[i]=v(i,14)*.3f;for(int i=0;i<FFDIM*MODEL;i++)b->w2[i]=v(i,15)*.3f;}
static int equal(const float*a,const float*b,uint64_t n){for(uint64_t i=0;i<n;i++)if(fabsf(a[i]-b[i])>4e-5f*fmaxf(1,fmaxf(fabsf(a[i]),fabsf(b[i]))))return 0;return 1;}
static double elapsed_ms(uint64_t ticks){mach_timebase_info_data_t t;mach_timebase_info(&t);return(double)ticks*t.numer/t.denom/1e6;}
static double bench(Block*b,unsigned reps,double*parts){ExecStep steps[14];Context ctx[14];emit(b,steps,ctx);uint64_t start=mach_absolute_time();for(unsigned r=0;r<reps;r++)tensor_transformer_steps_execute(steps,14);double full=elapsed_ms(mach_absolute_time()-start);static const uint8_t group[14]={0,3,3,3,1,2,0,3,4,0,3,0,3,4};for(unsigned g=0;g<5;g++){start=mach_absolute_time();for(unsigned r=0;r<reps;r++)for(unsigned i=0;i<14;i++)if(group[i]==g)run(&ctx[i]);parts[g]=elapsed_ms(mach_absolute_time()-start);}return full;}
int main(void){Dispatch scalar=scalar_dispatch(),automatic=auto_dispatch();Block reference,actual;initialize(&reference,&scalar);initialize(&actual,&automatic);ExecStep steps[14];Context ctx[14];emit(&reference,steps,ctx);for(unsigned i=0;i<14;i++)if(run(&ctx[i]))return 1;emit(&actual,steps,ctx);if(tensor_transformer_steps_execute(steps,14)||!equal(reference.out,actual.out,TOKENS*MODEL))return 1;for(int i=0;i<TOKENS;i++){float m=0;for(int j=0;j<MODEL;j++)m+=actual.out[i*MODEL+j];if(fabsf(m)>2e-4f)return 1;}double sp[5],ap[5],sms=bench(&reference,10000,sp),ams=bench(&actual,10000,ap);actual.generation++;if(tensor_transformer_steps_execute(steps,14)!=-4)return 1;printf("tensor transformer executor kernels passed: forward_actions=14 backend=%s scalar_reference=exact full_10k_ms=%.3f->%.3f speedup=%.2fx auto_parts_ms=matmul:%.3f,attention:%.3f,contiguous:%.3f,elementwise:%.3f,layernorm:%.3f lifetime=checked backward_contexts=pending\n",automatic.backend,sms,ams,sms/ams,ap[0],ap[1],ap[2],ap[3],ap[4]);return 0;}
