#ifndef TENSOR_TRANSFORMER_REFERENCE_SPIKE_H
#define TENSOR_TRANSFORMER_REFERENCE_SPIKE_H
/* Experimental shared reference implementation; not a stable core ABI. */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
enum{T=3,M=4,H=2,D=2,F=6,QW=3*M};
typedef struct{
 float x[T*M],wq[M*QW],wo[M*M],w1[M*F],w2[F*M];
 float qkv[T*QW],score[H*T*T],prob[H*T*T],head[H*T*D],merge[T*M],proj[T*M],s1[T*M],ln1[T*M],mean1[T],inv1[T],z1[T*F],act[T*F],ff[T*M],s2[T*M],out[T*M],mean2[T],inv2[T];
 float dx[T*M],dwq[M*QW],dwo[M*M],dw1[M*F],dw2[F*M];
}Block;
static float initv(int i,int s){return(float)(((i*37+s*17)%29)-14)/41.0f;}
static void mm(const float*a,const float*b,float*o,int r,int k,int c){memset(o,0,r*c*4);for(int i=0;i<r;i++)for(int j=0;j<c;j++)for(int p=0;p<k;p++)o[i*c+j]+=a[i*k+p]*b[p*c+j];}
static void mmback(const float*a,const float*b,const float*go,float*ga,float*gb,int r,int k,int c){for(int i=0;i<r;i++)for(int j=0;j<c;j++)for(int p=0;p<k;p++){float g=go[i*c+j];ga[i*k+p]+=g*b[p*c+j];gb[p*c+j]+=g*a[i*k+p];}}
static void ln(const float*x,float*y,float*mean,float*inv){for(int i=0;i<T;i++){float m=0,v=0;for(int j=0;j<M;j++)m+=x[i*M+j];m/=M;for(int j=0;j<M;j++){float q=x[i*M+j]-m;v+=q*q;}mean[i]=m;inv[i]=1/sqrtf(v/M+1e-5f);for(int j=0;j<M;j++)y[i*M+j]=(x[i*M+j]-m)*inv[i];}}
static void lnback(const float*x,const float*gy,float*gx,const float*mean,const float*inv){for(int i=0;i<T;i++){float sum=0,sumh=0;for(int j=0;j<M;j++){float h=(x[i*M+j]-mean[i])*inv[i];sum+=gy[i*M+j];sumh+=gy[i*M+j]*h;}for(int j=0;j<M;j++){float h=(x[i*M+j]-mean[i])*inv[i];gx[i*M+j]+=inv[i]*(gy[i*M+j]-(sum+h*sumh)/M);}}}
static void forward(Block*b){mm(b->x,b->wq,b->qkv,T,M,QW);float scale=1/sqrtf(D);for(int h=0;h<H;h++)for(int i=0;i<T;i++){float mx=-INFINITY;for(int j=0;j<T;j++){float s=0;for(int d=0;d<D;d++)s+=b->qkv[i*QW+h*D+d]*b->qkv[j*QW+M+h*D+d];s*=scale;b->score[(h*T+i)*T+j]=s;mx=fmaxf(mx,s);}float total=0;for(int j=0;j<T;j++){float e=expf(b->score[(h*T+i)*T+j]-mx);b->prob[(h*T+i)*T+j]=e;total+=e;}for(int j=0;j<T;j++)b->prob[(h*T+i)*T+j]/=total;for(int d=0;d<D;d++){float s=0;for(int j=0;j<T;j++)s+=b->prob[(h*T+i)*T+j]*b->qkv[j*QW+2*M+h*D+d];b->head[(h*T+i)*D+d]=s;b->merge[i*M+h*D+d]=s;}}mm(b->merge,b->wo,b->proj,T,M,M);for(int i=0;i<T*M;i++)b->s1[i]=b->x[i]+b->proj[i];ln(b->s1,b->ln1,b->mean1,b->inv1);mm(b->ln1,b->w1,b->z1,T,M,F);for(int i=0;i<T*F;i++)b->act[i]=b->z1[i]>0?b->z1[i]:0;mm(b->act,b->w2,b->ff,T,F,M);for(int i=0;i<T*M;i++)b->s2[i]=b->ln1[i]+b->ff[i];ln(b->s2,b->out,b->mean2,b->inv2);}
static float loss(Block*b,const float*seed){forward(b);float z=0;for(int i=0;i<T*M;i++)z+=b->out[i]*seed[i];return z;}
static void backward(Block*b,const float*gout){float ds2[T*M]={0},dln1[T*M]={0},dff[T*M]={0},dact[T*F]={0},dz1[T*F]={0},ds1[T*M]={0},dproj[T*M]={0},dmerge[T*M]={0},dhead[H*T*D]={0},dprob[H*T*T]={0},dscore[H*T*T]={0},dqkv[T*QW]={0};memset(b->dx,0,sizeof b->dx);memset(b->dwq,0,sizeof b->dwq);memset(b->dwo,0,sizeof b->dwo);memset(b->dw1,0,sizeof b->dw1);memset(b->dw2,0,sizeof b->dw2);lnback(b->s2,gout,ds2,b->mean2,b->inv2);for(int i=0;i<T*M;i++)dln1[i]+=ds2[i],dff[i]+=ds2[i];mmback(b->act,b->w2,dff,dact,b->dw2,T,F,M);for(int i=0;i<T*F;i++)dz1[i]=b->z1[i]>0?dact[i]:0;mmback(b->ln1,b->w1,dz1,dln1,b->dw1,T,M,F);lnback(b->s1,dln1,ds1,b->mean1,b->inv1);for(int i=0;i<T*M;i++)b->dx[i]+=ds1[i],dproj[i]+=ds1[i];mmback(b->merge,b->wo,dproj,dmerge,b->dwo,T,M,M);for(int h=0;h<H;h++)for(int i=0;i<T;i++)for(int d=0;d<D;d++)dhead[(h*T+i)*D+d]=dmerge[i*M+h*D+d];for(int h=0;h<H;h++)for(int i=0;i<T;i++)for(int j=0;j<T;j++)for(int d=0;d<D;d++){float g=dhead[(h*T+i)*D+d];dprob[(h*T+i)*T+j]+=g*b->qkv[j*QW+2*M+h*D+d];dqkv[j*QW+2*M+h*D+d]+=g*b->prob[(h*T+i)*T+j];}for(int h=0;h<H;h++)for(int i=0;i<T;i++){float dot=0;for(int j=0;j<T;j++)dot+=dprob[(h*T+i)*T+j]*b->prob[(h*T+i)*T+j];for(int j=0;j<T;j++)dscore[(h*T+i)*T+j]=b->prob[(h*T+i)*T+j]*(dprob[(h*T+i)*T+j]-dot);}float scale=1/sqrtf(D);for(int h=0;h<H;h++)for(int i=0;i<T;i++)for(int j=0;j<T;j++)for(int d=0;d<D;d++){float g=dscore[(h*T+i)*T+j]*scale;dqkv[i*QW+h*D+d]+=g*b->qkv[j*QW+M+h*D+d];dqkv[j*QW+M+h*D+d]+=g*b->qkv[i*QW+h*D+d];}mmback(b->x,b->wq,dqkv,b->dx,b->dwq,T,M,QW);}
static int check(Block*b,float*param,float*grad,int count,int pos,const float*seed,const char*name){float old=param[pos],eps=1e-3f;param[pos]=old+eps;float plus=loss(b,seed);param[pos]=old-eps;float minus=loss(b,seed);param[pos]=old;float numeric=(plus-minus)/(2*eps),analytic=grad[pos],tol=5e-3f*fmaxf(1,fmaxf(fabsf(numeric),fabsf(analytic)));if(fabsf(numeric-analytic)>tol){fprintf(stderr,"transformer backward %s analytic=%g numeric=%g\n",name,analytic,numeric);return 1;}return 0;}
#ifndef TRANSFORMER_REFERENCE_NO_MAIN
int main(void){Block b={0};float seed[T*M];for(int i=0;i<T*M;i++)b.x[i]=initv(i,1),seed[i]=initv(i,6);for(int i=0;i<M*QW;i++)b.wq[i]=initv(i,2)*.4f;for(int i=0;i<M*M;i++)b.wo[i]=initv(i,3)*.4f;for(int i=0;i<M*F;i++)b.w1[i]=initv(i,4)*.5f;for(int i=0;i<F*M;i++)b.w2[i]=initv(i,5)*.5f;forward(&b);backward(&b,seed);if(check(&b,b.x,b.dx,T*M,T*M/2,seed,"x")||check(&b,b.wq,b.dwq,M*QW,M*QW/3,seed,"wqkv")||check(&b,b.wo,b.dwo,M*M,M*M/2,seed,"wo")||check(&b,b.w1,b.dw1,M*F,M*F/3,seed,"w1")||check(&b,b.w2,b.dw2,F*M,F*M/2,seed,"w2"))return 1;printf("tensor transformer block backward passed: shape=[1,3,4] heads=2 ffn=6 probes=x,wqkv,wo,w1,w2 oracle=finite-difference chain=attention+2LayerNorm+FFN\n");return 0;}
#endif
#endif
