#ifndef TENSOR_PLAN_TRACE_SPIKE_H
#define TENSOR_PLAN_TRACE_SPIKE_H
/* Experimental observability layer. It consumes planner alternatives and
   decisions; it does not own graph semantics or lowering. */
#include <stdint.h>
#include <stdio.h>
#include <string.h>
enum { TRACE_MAX_ALTS=8, TRACE_MAX_DECISIONS=16 };
enum { COST_BYTES, COST_NS, COST_ACTIONS };
enum { SOURCE_DEFAULT, SOURCE_MEASURED, SOURCE_CACHED };
typedef struct {char name[32];uint64_t peak_bytes,compute_cost,actions;uint32_t feasible;} PlanAlternative;
typedef struct {char source[12],host[32],compiler[32],build[24],revision[16];uint32_t samples;double median,min,max;uint32_t uncertain;} MeasurementProvenance;
typedef struct {char subject[32],constraint[64],reason[128];PlanAlternative alternatives[TRACE_MAX_ALTS];uint32_t alternative_count,chosen,cost_kind;uint64_t budget,counterfactual_budget;int32_t counterfactual_choice;MeasurementProvenance provenance;} PlanDecisionTrace;
typedef struct {PlanDecisionTrace decisions[TRACE_MAX_DECISIONS];uint32_t count;} PlanTrace;

static int trace_choose_memory(PlanTrace*t,const char*subject,const PlanAlternative*a,uint32_t n,uint64_t budget,uint64_t counterfactual){
    if(t->count==TRACE_MAX_DECISIONS||!n||n>TRACE_MAX_ALTS)return-1;PlanDecisionTrace*d=&t->decisions[t->count++];memset(d,0,sizeof*d);snprintf(d->subject,sizeof d->subject,"%s",subject);d->alternative_count=n;d->budget=budget;d->counterfactual_budget=counterfactual;d->cost_kind=COST_BYTES;d->chosen=UINT32_MAX;d->counterfactual_choice=-1;
    uint64_t best=UINT64_MAX,cf_best=UINT64_MAX;for(uint32_t i=0;i<n;i++){d->alternatives[i]=a[i];if(a[i].feasible&&a[i].peak_bytes<=budget&&a[i].compute_cost<best){best=a[i].compute_cost;d->chosen=i;}if(a[i].feasible&&a[i].peak_bytes<=counterfactual&&a[i].compute_cost<cf_best){cf_best=a[i].compute_cost;d->counterfactual_choice=(int32_t)i;}}
    if(d->chosen==UINT32_MAX)return-2;snprintf(d->constraint,sizeof d->constraint,"peak_bytes <= %llu",(unsigned long long)budget);snprintf(d->reason,sizeof d->reason,"lowest compute cost among memory-feasible alternatives");return 0;}
static int trace_add_measured(PlanTrace*t,const char*subject,const PlanAlternative*a,uint32_t n,uint32_t chosen,MeasurementProvenance p,const char*reason){if(t->count==TRACE_MAX_DECISIONS||!n||n>TRACE_MAX_ALTS||chosen>=n)return-1;PlanDecisionTrace*d=&t->decisions[t->count++];memset(d,0,sizeof*d);snprintf(d->subject,sizeof d->subject,"%s",subject);memcpy(d->alternatives,a,n*sizeof*a);d->alternative_count=n;d->chosen=chosen;d->counterfactual_choice=-1;d->cost_kind=COST_NS;d->provenance=p;snprintf(d->constraint,sizeof d->constraint,"measurement confidence");snprintf(d->reason,sizeof d->reason,"%s",reason);return 0;}
static int trace_verify_actions(const PlanDecisionTrace*d,uint64_t actual){return d->chosen<d->alternative_count&&d->alternatives[d->chosen].actions==actual?0:-1;}
static int trace_explain(FILE*f,const PlanTrace*t){for(uint32_t x=0;x<t->count;x++){const PlanDecisionTrace*d=&t->decisions[x];if(fprintf(f,"decision: %s\n",d->subject)<0)return-1;for(uint32_t i=0;i<d->alternative_count;i++)if(fprintf(f,"  %c %-20s peak=%llu cost=%llu actions=%llu%s\n",i==d->chosen?'*':' ',d->alternatives[i].name,(unsigned long long)d->alternatives[i].peak_bytes,(unsigned long long)d->alternatives[i].compute_cost,(unsigned long long)d->alternatives[i].actions,d->alternatives[i].feasible?"":" infeasible")<0)return-1;if(fprintf(f,"  constraint: %s\n  chosen: %s\n  reason: %s\n",d->constraint,d->alternatives[d->chosen].name,d->reason)<0)return-1;if(d->counterfactual_choice>=0&&fprintf(f,"  counterfactual budget=%llu -> %s\n",(unsigned long long)d->counterfactual_budget,d->alternatives[d->counterfactual_choice].name)<0)return-1;if(d->provenance.source[0]&&fprintf(f,"  evidence: source=%s host=%s compiler=%s revision=%s samples=%u median=%.3f range=[%.3f,%.3f] confidence=%s\n",d->provenance.source,d->provenance.host,d->provenance.compiler,d->provenance.revision,d->provenance.samples,d->provenance.median,d->provenance.min,d->provenance.max,d->provenance.uncertain?"uncertain":"confident")<0)return-1;}return 0;}
static int trace_export_tsv(FILE*f,const PlanTrace*t){if(fprintf(f,"decision\talternative\tchosen\tfeasible\tpeak_bytes\tcompute_cost\tactions\tbudget\tsource\thost\tcompiler\trevision\tsamples\tmedian\tmin\tmax\tuncertain\treason\n")<0)return-1;for(uint32_t x=0;x<t->count;x++){const PlanDecisionTrace*d=&t->decisions[x];for(uint32_t i=0;i<d->alternative_count;i++)if(fprintf(f,"%s\t%s\t%u\t%u\t%llu\t%llu\t%llu\t%llu\t%s\t%s\t%s\t%s\t%u\t%.3f\t%.3f\t%.3f\t%u\t%s\n",d->subject,d->alternatives[i].name,i==d->chosen,d->alternatives[i].feasible,(unsigned long long)d->alternatives[i].peak_bytes,(unsigned long long)d->alternatives[i].compute_cost,(unsigned long long)d->alternatives[i].actions,(unsigned long long)d->budget,d->provenance.source,d->provenance.host,d->provenance.compiler,d->provenance.revision,d->provenance.samples,d->provenance.median,d->provenance.min,d->provenance.max,d->provenance.uncertain,d->reason)<0)return-1;}return 0;}
#endif
