#ifndef TENSOR_PLAN_DIFF_SPIKE_H
#define TENSOR_PLAN_DIFF_SPIKE_H
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
enum { DIFF_MAX_ROWS=128, DIFF_MAX_FILE=131072 };
typedef struct{char decision[32],alternative[32],source[12],host[32],compiler[48],revision[16],reason[128];unsigned chosen,feasible,uncertain,samples;unsigned long long peak,cost,actions,budget;double median,min,max;}TraceRow;
typedef struct{TraceRow row[DIFF_MAX_ROWS];unsigned count;}ParsedTrace;
static const char*diff_header="decision\talternative\tchosen\tfeasible\tpeak_bytes\tcompute_cost\tactions\tbudget\tsource\thost\tcompiler\trevision\tsamples\tmedian\tmin\tmax\tuncertain\treason";
static int fields(char*line,char**out,unsigned cap){unsigned n=0;char*p=line;for(;;){if(n==cap)return-1;out[n++]=p;char*t=strchr(p,'\t');if(!t)break;*t=0;p=t+1;}return(int)n;}
static int parse_trace_text(char*text,ParsedTrace*out,char*error,size_t error_n){memset(out,0,sizeof*out);char*save=NULL,*line=strtok_r(text,"\n",&save);if(!line||strcmp(line,diff_header)){snprintf(error,error_n,"incompatible trace header");return-1;}unsigned lineno=1;while((line=strtok_r(NULL,"\n",&save))){lineno++;if(!*line)continue;if(out->count==DIFF_MAX_ROWS){snprintf(error,error_n,"too many trace rows");return-1;}char*f[18];if(fields(line,f,18)!=18){snprintf(error,error_n,"line %u: expected 18 columns",lineno);return-1;}TraceRow*r=&out->row[out->count++];snprintf(r->decision,sizeof r->decision,"%s",f[0]);snprintf(r->alternative,sizeof r->alternative,"%s",f[1]);if(!r->decision[0]||!r->alternative[0]){snprintf(error,error_n,"line %u: empty identity",lineno);return-1;}char*end;r->chosen=(unsigned)strtoul(f[2],&end,10);if(*end||r->chosen>1)return-1;r->feasible=(unsigned)strtoul(f[3],&end,10);if(*end||r->feasible>1)return-1;r->peak=strtoull(f[4],&end,10);if(*end)return-1;r->cost=strtoull(f[5],&end,10);if(*end)return-1;r->actions=strtoull(f[6],&end,10);if(*end)return-1;r->budget=strtoull(f[7],&end,10);if(*end)return-1;snprintf(r->source,sizeof r->source,"%s",f[8]);snprintf(r->host,sizeof r->host,"%s",f[9]);snprintf(r->compiler,sizeof r->compiler,"%s",f[10]);snprintf(r->revision,sizeof r->revision,"%s",f[11]);r->samples=(unsigned)strtoul(f[12],&end,10);if(*end)return-1;r->median=strtod(f[13],&end);if(*end)return-1;r->min=strtod(f[14],&end);if(*end)return-1;r->max=strtod(f[15],&end);if(*end)return-1;r->uncertain=(unsigned)strtoul(f[16],&end,10);if(*end||r->uncertain>1)return-1;snprintf(r->reason,sizeof r->reason,"%s",f[17]);for(unsigned i=0;i+1<out->count;i++)if(!strcmp(out->row[i].decision,r->decision)&&!strcmp(out->row[i].alternative,r->alternative)){snprintf(error,error_n,"line %u: duplicate decision/alternative",lineno);return-1;}}
    if(!out->count){snprintf(error,error_n,"empty trace");return-1;}return 0;}
static const TraceRow*find_row(const ParsedTrace*t,const char*d,const char*a){for(unsigned i=0;i<t->count;i++)if(!strcmp(t->row[i].decision,d)&&!strcmp(t->row[i].alternative,a))return&t->row[i];return NULL;}
static const TraceRow*chosen_row(const ParsedTrace*t,const char*d){const TraceRow*found=NULL;for(unsigned i=0;i<t->count;i++)if(!strcmp(t->row[i].decision,d)&&t->row[i].chosen){if(found)return NULL;found=&t->row[i];}return found;}
static int emit_change(FILE*h,FILE*m,const char*kind,const char*subject,const char*before,const char*after){if(h&&fprintf(h,"%s: %s -> %s\n",subject,before,after)<0)return-1;if(m&&fprintf(m,"%s\t%s\t%s\t%s\n",kind,subject,before,after)<0)return-1;return 0;}
static int diff_traces(const ParsedTrace*a,const ParsedTrace*b,FILE*human,FILE*machine){unsigned changes=0;if(machine)fprintf(machine,"kind\tsubject\tbefore\tafter\n");for(unsigned i=0;i<a->count;i++){const TraceRow*r=&a->row[i];int first=1;for(unsigned j=0;j<i;j++)if(!strcmp(a->row[j].decision,r->decision))first=0;if(!first)continue;const TraceRow*ca=chosen_row(a,r->decision),*cb=chosen_row(b,r->decision);if(!ca||!cb){if(emit_change(human,machine,"decision","decision-set",ca?ca->decision:"present",cb?cb->decision:"missing"))return-1;changes++;continue;}if(strcmp(ca->alternative,cb->alternative)){if(emit_change(human,machine,"choice",r->decision,ca->alternative,cb->alternative))return-1;changes++;}char x[160],y[160],subject[64];if(ca->peak!=cb->peak){snprintf(x,sizeof x,"%llu bytes",ca->peak);snprintf(y,sizeof y,"%llu bytes",cb->peak);snprintf(subject,sizeof subject,"%s.peak",r->decision);emit_change(human,machine,"peak",subject,x,y);changes++;}if(ca->actions!=cb->actions){snprintf(x,sizeof x,"%llu",ca->actions);snprintf(y,sizeof y,"%llu",cb->actions);snprintf(subject,sizeof subject,"%s.actions",r->decision);emit_change(human,machine,"actions",subject,x,y);changes++;}if(ca->budget!=cb->budget){snprintf(x,sizeof x,"%llu",ca->budget);snprintf(y,sizeof y,"%llu",cb->budget);snprintf(subject,sizeof subject,"%s.budget",r->decision);emit_change(human,machine,"budget",subject,x,y);changes++;}if(ca->median!=cb->median){snprintf(x,sizeof x,"%.3f",ca->median);snprintf(y,sizeof y,"%.3f",cb->median);snprintf(subject,sizeof subject,"%s.median",r->decision);emit_change(human,machine,"median",subject,x,y);changes++;}if(ca->uncertain!=cb->uncertain){snprintf(subject,sizeof subject,"%s.confidence",r->decision);emit_change(human,machine,"confidence",subject,ca->uncertain?"uncertain":"confident",cb->uncertain?"uncertain":"confident");changes++;}if(strcmp(ca->source,cb->source)||strcmp(ca->host,cb->host)||strcmp(ca->compiler,cb->compiler)||strcmp(ca->revision,cb->revision)){snprintf(x,sizeof x,"%s/%s/%s/%s",ca->source,ca->host,ca->compiler,ca->revision);snprintf(y,sizeof y,"%s/%s/%s/%s",cb->source,cb->host,cb->compiler,cb->revision);snprintf(subject,sizeof subject,"%s.provenance",r->decision);emit_change(human,machine,"provenance",subject,x,y);changes++;}}
    for(unsigned pass=0;pass<2;pass++){const ParsedTrace*x=pass?b:a,*y=pass?a:b;for(unsigned i=0;i<x->count;i++)if(!find_row(y,x->row[i].decision,x->row[i].alternative)){emit_change(human,machine,pass?"alternative-added":"alternative-removed",x->row[i].decision,pass?"absent":x->row[i].alternative,pass?x->row[i].alternative:"absent");changes++;}}
    if(!changes&&human)fputs("no semantic changes\n",human);return(int)changes;}
#endif
