#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
typedef struct{float*data,*grad;uint64_t rows,cols;}Tensor;
extern int tensor_matmul_forward_f32(const Tensor*,const Tensor*,Tensor*);
enum Action{QKV_PROJECTION,VIEW_Q,VIEW_K,VIEW_V,ATTENTION,CONTIGUOUS_MERGE,OUTPUT_PROJECTION,RESIDUAL_LAYERNORM,FFN_LINEAR_RELU,FFN_LINEAR,RESIDUAL_LAYERNORM_2};
typedef struct{enum Action kind;uint64_t rows,cols,scratch_offset;}PlanStep;
static float*af(uint64_t n){float*p=calloc(n,sizeof(float));if(!p)exit(2);return p;}static float val(uint64_t i,uint64_t s){return(float)((int)((i*37+s*19)%31)-15)/47.0f;}
static void bias_relu(float*x,const float*b,uint64_t rows,uint64_t cols,int relu){for(uint64_t i=0;i<rows;i++)for(uint64_t j=0;j<cols;j++){float v=x[i*cols+j]+b[j];x[i*cols+j]=relu&&v<0?0:v;}}
static void layernorm_residual(const float*x,const float*skip,float*out,float*mean,float*inv,uint64_t rows,uint64_t cols){for(uint64_t i=0;i<rows;i++){float m=0,v=0;for(uint64_t j=0;j<cols;j++)m+=x[i*cols+j]+skip[i*cols+j];m/=cols;for(uint64_t j=0;j<cols;j++){float d=x[i*cols+j]+skip[i*cols+j]-m;v+=d*d;}float iv=1/sqrtf(v/cols+1e-5f);mean[i]=m;inv[i]=iv;for(uint64_t j=0;j<cols;j++)out[i*cols+j]=(x[i*cols+j]+skip[i*cols+j]-m)*iv;}}
static void attention_from_packed(const float*packed,float*merged,float*scores,float*weights,uint64_t tokens,uint64_t heads,uint64_t dim){uint64_t model=heads*dim,width=3*model;float scale=1/sqrtf((float)dim);for(uint64_t h=0;h<heads;h++)for(uint64_t i=0;i<tokens;i++){float max=-INFINITY;for(uint64_t j=0;j<tokens;j++){float s=0;for(uint64_t d=0;d<dim;d++)s+=packed[i*width+h*dim+d]*packed[j*width+model+h*dim+d];s*=scale;scores[(h*tokens+i)*tokens+j]=s;if(s>max)max=s;}float total=0;for(uint64_t j=0;j<tokens;j++){float e=expf(scores[(h*tokens+i)*tokens+j]-max);weights[(h*tokens+i)*tokens+j]=e;total+=e;}for(uint64_t j=0;j<tokens;j++)weights[(h*tokens+i)*tokens+j]/=total;for(uint64_t d=0;d<dim;d++){float sum=0;for(uint64_t j=0;j<tokens;j++)sum+=weights[(h*tokens+i)*tokens+j]*packed[j*width+2*model+h*dim+d];merged[i*model+h*dim+d]=sum;}}}
static int one(uint64_t tokens,uint64_t*peak_out){const uint64_t model=8,heads=2,dim=4,ff=16,qkvn=tokens*3*model,attn=tokens*tokens*heads,mn=tokens*model,ffn=tokens*ff;float*x=af(mn),*wqkv=af(model*3*model),*packed=af(qkvn),*scores=af(attn),*weights=af(attn),*merged=af(mn),*wo=af(model*model),*proj=af(mn),*ln1=af(mn),*w1=af(model*ff),*hidden=af(ffn),*w2=af(ff*model),*ffout=af(mn),*out=af(mn),*bq=af(3*model),*bo=af(model),*b1=af(ff),*b2=af(model),*mean1=af(tokens),*inv1=af(tokens),*mean2=af(tokens),*inv2=af(tokens);for(uint64_t i=0;i<mn;i++)x[i]=val(i,1);for(uint64_t i=0;i<model*3*model;i++)wqkv[i]=val(i,2);for(uint64_t i=0;i<model*model;i++)wo[i]=val(i,3);for(uint64_t i=0;i<model*ff;i++)w1[i]=val(i,4);for(uint64_t i=0;i<ff*model;i++)w2[i]=val(i,5);Tensor tx={x,0,tokens,model},twq={wqkv,0,model,3*model},tp={packed,0,tokens,3*model};if(tensor_matmul_forward_f32(&tx,&twq,&tp))return 1;bias_relu(packed,bq,tokens,3*model,0);attention_from_packed(packed,merged,scores,weights,tokens,heads,dim);Tensor tm={merged,0,tokens,model},two={wo,0,model,model},tproj={proj,0,tokens,model};tensor_matmul_forward_f32(&tm,&two,&tproj);bias_relu(proj,bo,tokens,model,0);layernorm_residual(proj,x,ln1,mean1,inv1,tokens,model);Tensor tl={ln1,0,tokens,model},tw1={w1,0,model,ff},th={hidden,0,tokens,ff};tensor_matmul_forward_f32(&tl,&tw1,&th);bias_relu(hidden,b1,tokens,ff,1);Tensor th2={hidden,0,tokens,ff},tw2={w2,0,ff,model},tf={ffout,0,tokens,model};tensor_matmul_forward_f32(&th2,&tw2,&tf);bias_relu(ffout,b2,tokens,model,0);layernorm_residual(ffout,ln1,out,mean2,inv2,tokens,model);for(uint64_t i=0;i<tokens;i++){float mean=0,var=0,rowsum=0;for(uint64_t j=0;j<model;j++)mean+=out[i*model+j];mean/=model;for(uint64_t j=0;j<model;j++){float d=out[i*model+j]-mean;var+=d*d;}for(uint64_t h=0;h<heads;h++)for(uint64_t j=0;j<tokens;j++)rowsum+=weights[(h*tokens+i)*tokens+j];if(fabsf(mean)>2e-5f||fabsf(var/model-1)>2e-3f||fabsf(rowsum-heads)>2e-5f)return 1;}uint64_t peak=qkvn+2*attn+mn+ffn+2*mn;if(peak>*peak_out)*peak_out=peak;float*all[]={x,wqkv,packed,scores,weights,merged,wo,proj,ln1,w1,hidden,w2,ffout,out,bq,bo,b1,b2,mean1,inv1,mean2,inv2};for(unsigned i=0;i<22;i++)free(all[i]);return 0;}
int main(void){PlanStep plan[]={{QKV_PROJECTION,0,24,0},{VIEW_Q,0,0,0},{VIEW_K,0,0,0},{VIEW_V,0,0,0},{ATTENTION,0,0,0},{CONTIGUOUS_MERGE,0,8,0},{OUTPUT_PROJECTION,0,8,0},{RESIDUAL_LAYERNORM,0,8,0},{FFN_LINEAR_RELU,0,16,0},{FFN_LINEAR,0,8,0},{RESIDUAL_LAYERNORM_2,0,8,0}};uint64_t dims[]={7,8,9},peak=0;for(unsigned i=0;i<3;i++)if(one(dims[i],&peak))return 1;printf("tensor transformer block forward passed: cases=3 tokens=7/8/9 model=8 heads=2 head_dim=4 ffn=16 plan_steps=%zu views=3 contiguous_actions=1 layernorm=2 scratch_floats_peak=%llu backward=pending\n",sizeof(plan)/sizeof(plan[0]),(unsigned long long)peak);return 0;}
