#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
typedef struct{float*data,*grad;uint64_t rows,cols;}Tensor;
static float*af(uint64_t n){float*p=calloc(n,sizeof(float));if(!p)exit(2);return p;}static float val(uint64_t i,uint64_t s){return(float)((int)((i*37+s*13)%31)-15)/17.0f;}
static int residual_forward(const Tensor*a,const Tensor*b,Tensor*out){if(a->rows!=b->rows||a->cols!=b->cols||out->rows!=a->rows||out->cols!=a->cols)return-1;for(uint64_t i=0;i<a->rows*a->cols;i++)out->data[i]=a->data[i]+b->data[i];return 0;}
static int residual_backward(Tensor*a,Tensor*b,const Tensor*out){if(!a->grad||!b->grad||!out->grad)return-1;for(uint64_t i=0;i<a->rows*a->cols;i++)a->grad[i]+=out->grad[i],b->grad[i]+=out->grad[i];return 0;}
static int layernorm_forward(const Tensor*x,const Tensor*gamma,const Tensor*beta,Tensor*y,float*mean,float*inv,float eps){if(x->rows!=y->rows||x->cols!=y->cols||gamma->rows!=1||beta->rows!=1||gamma->cols!=x->cols||beta->cols!=x->cols)return-1;for(uint64_t r=0;r<x->rows;r++){float m=0,v=0;for(uint64_t c=0;c<x->cols;c++)m+=x->data[r*x->cols+c];m/=x->cols;for(uint64_t c=0;c<x->cols;c++){float d=x->data[r*x->cols+c]-m;v+=d*d;}v/=x->cols;mean[r]=m;inv[r]=1/sqrtf(v+eps);for(uint64_t c=0;c<x->cols;c++){float h=(x->data[r*x->cols+c]-m)*inv[r];y->data[r*x->cols+c]=h*gamma->data[c]+beta->data[c];}}return 0;}
static int layernorm_backward(Tensor*x,Tensor*gamma,Tensor*beta,const Tensor*y,const float*mean,const float*inv){if(!x->grad||!gamma->grad||!beta->grad||!y->grad)return-1;for(uint64_t r=0;r<x->rows;r++){float sum=0,sumh=0;for(uint64_t c=0;c<x->cols;c++){float h=(x->data[r*x->cols+c]-mean[r])*inv[r],g=y->grad[r*x->cols+c]*gamma->data[c];sum+=g;sumh+=g*h;gamma->grad[c]+=y->grad[r*x->cols+c]*h;beta->grad[c]+=y->grad[r*x->cols+c];}for(uint64_t c=0;c<x->cols;c++){float h=(x->data[r*x->cols+c]-mean[r])*inv[r],g=y->grad[r*x->cols+c]*gamma->data[c];x->grad[r*x->cols+c]+=inv[r]*(g-(sum+h*sumh)/x->cols);}}return 0;}
static float objective(Tensor*x,Tensor*skip,Tensor*gamma,Tensor*beta,Tensor*sum,Tensor*y,float*m,float*iv,const float*seed){residual_forward(x,skip,sum);layernorm_forward(sum,gamma,beta,y,m,iv,1e-5f);float z=0;for(uint64_t i=0;i<y->rows*y->cols;i++)z+=y->data[i]*seed[i];return z;}
static int closef(float a,float b){return fabsf(a-b)<=4e-3f*fmaxf(1,fmaxf(fabsf(a),fabsf(b)));}
static int one(uint64_t cols){uint64_t rows=14,n=rows*cols;Tensor x={af(n),af(n),rows,cols},skip={af(n),af(n),rows,cols},sum={af(n),af(n),rows,cols},g={af(cols),af(cols),1,cols},b={af(cols),af(cols),1,cols},y={af(n),af(n),rows,cols};float*m=af(rows),*iv=af(rows),*seed=af(n);for(uint64_t i=0;i<n;i++)x.data[i]=val(i,1),skip.data[i]=val(i,2)*.2f,seed[i]=val(i,3);for(uint64_t i=0;i<cols;i++)g.data[i]=1+val(i,4)*.1f,b.data[i]=val(i,5)*.1f;objective(&x,&skip,&g,&b,&sum,&y,m,iv,seed);memcpy(y.grad,seed,n*4);if(layernorm_backward(&sum,&g,&b,&y,m,iv)||residual_backward(&x,&skip,&sum))return 1;Tensor*probe[]={&x,&skip,&g,&b};for(unsigned p=0;p<4;p++){uint64_t count=probe[p]->rows*probe[p]->cols,pos=count/2;float analytic=probe[p]->grad[pos],old=probe[p]->data[pos],eps=1e-3f;probe[p]->data[pos]=old+eps;float plus=objective(&x,&skip,&g,&b,&sum,&y,m,iv,seed);probe[p]->data[pos]=old-eps;float minus=objective(&x,&skip,&g,&b,&sum,&y,m,iv,seed);probe[p]->data[pos]=old;if(!closef(analytic,(plus-minus)/(2*eps))){fprintf(stderr,"layernorm gradient mismatch cols=%llu probe=%u analytic=%g numeric=%g\n",cols,p,analytic,(plus-minus)/(2*eps));return 1;}}Tensor*all[]={&x,&skip,&sum,&g,&b,&y};for(unsigned i=0;i<6;i++)free(all[i]->data),free(all[i]->grad);free(m);free(iv);free(seed);return 0;}
int main(void){uint64_t dims[]={7,8,9};for(unsigned i=0;i<3;i++)if(one(dims[i]))return 1;printf("tensor residual+LayerNorm passed: rows=14 features=7/8/9 eps=1e-5 saved=mean+invstd forward=stable backward=finite-difference\n");return 0;}
