#ifndef TENSOR_TRANSFORMER_EXECUTOR_SPIKE_H
#define TENSOR_TRANSFORMER_EXECUTOR_SPIKE_H
/* Experimental scheduled-backward contexts; not a stable core ABI. */
#define TRANSFORMER_REFERENCE_NO_MAIN
#include "tensor_transformer_reference_spike.h"
#undef TRANSFORMER_REFERENCE_NO_MAIN
#include <stdint.h>
#include <stdio.h>
#include <string.h>
typedef struct{int(*run)(void*);void*context;uint32_t kind,flags;uint64_t reserved;}ExecStep;
enum{ZERO_ACTION,REVERSE_ACTION,REMAT_ACTION};
typedef struct{float ds2[T*M],dln1[T*M],dff[T*M],dact[T*F],dz1[T*F],ds1[T*M],dproj[T*M],dmerge[T*M],dhead[H*T*D],dprob[H*T*T],dscore[H*T*T],dqkv[T*QW];}Scratch;
typedef struct{Block*b;Scratch*s;const float*seed;uint32_t kind,index,generation,*live_generation;}Context;
extern int tensor_transformer_steps_execute(const ExecStep*,uint64_t);
static int zero_one(Context*c){switch(c->index){case 0:memset(c->b->dx,0,sizeof c->b->dx);break;case 1:memset(c->b->dwq,0,sizeof c->b->dwq);break;case 2:memset(c->b->dwo,0,sizeof c->b->dwo);break;case 3:memset(c->b->dw1,0,sizeof c->b->dw1);break;case 4:memset(c->b->dw2,0,sizeof c->b->dw2);break;case 5:memset(c->s->ds2,0,sizeof c->s->ds2);memset(c->s->dln1,0,sizeof c->s->dln1);memset(c->s->dff,0,sizeof c->s->dff);break;case 6:memset(c->s->dact,0,sizeof c->s->dact);memset(c->s->dz1,0,sizeof c->s->dz1);memset(c->s->ds1,0,sizeof c->s->ds1);break;case 7:memset(c->s->dproj,0,sizeof c->s->dproj);memset(c->s->dmerge,0,sizeof c->s->dmerge);memset(c->s->dhead,0,sizeof c->s->dhead);break;case 8:memset(c->s->dprob,0,sizeof c->s->dprob);memset(c->s->dscore,0,sizeof c->s->dscore);memset(c->s->dqkv,0,sizeof c->s->dqkv);break;default:return-1;}return 0;}
static int reverse_one(Context*c){Block*b=c->b;Scratch*s=c->s;switch(c->index){case 0:lnback(b->s2,c->seed,s->ds2,b->mean2,b->inv2);break;case 1:for(int i=0;i<T*M;i++)s->dln1[i]+=s->ds2[i],s->dff[i]+=s->ds2[i];break;case 2:mmback(b->act,b->w2,s->dff,s->dact,b->dw2,T,F,M);break;case 3:for(int i=0;i<T*F;i++)s->dz1[i]=b->z1[i]>0?s->dact[i]:0;break;case 4:mmback(b->ln1,b->w1,s->dz1,s->dln1,b->dw1,T,M,F);break;case 5:lnback(b->s1,s->dln1,s->ds1,b->mean1,b->inv1);break;case 6:for(int i=0;i<T*M;i++)b->dx[i]+=s->ds1[i],s->dproj[i]+=s->ds1[i];break;case 7:mmback(b->merge,b->wo,s->dproj,s->dmerge,b->dwo,T,M,M);break;case 8:for(int h=0;h<H;h++)for(int i=0;i<T;i++)for(int d=0;d<D;d++)s->dhead[(h*T+i)*D+d]=s->dmerge[i*M+h*D+d];break;case 9:{for(int h=0;h<H;h++)for(int i=0;i<T;i++)for(int j=0;j<T;j++)for(int d=0;d<D;d++){float g=s->dhead[(h*T+i)*D+d];s->dprob[(h*T+i)*T+j]+=g*b->qkv[j*QW+2*M+h*D+d];s->dqkv[j*QW+2*M+h*D+d]+=g*b->prob[(h*T+i)*T+j];}for(int h=0;h<H;h++)for(int i=0;i<T;i++){float dot=0;for(int j=0;j<T;j++)dot+=s->dprob[(h*T+i)*T+j]*b->prob[(h*T+i)*T+j];for(int j=0;j<T;j++)s->dscore[(h*T+i)*T+j]=b->prob[(h*T+i)*T+j]*(s->dprob[(h*T+i)*T+j]-dot);}float scale=1/sqrtf(D);for(int h=0;h<H;h++)for(int i=0;i<T;i++)for(int j=0;j<T;j++)for(int d=0;d<D;d++){float g=s->dscore[(h*T+i)*T+j]*scale;s->dqkv[i*QW+h*D+d]+=g*b->qkv[j*QW+M+h*D+d];s->dqkv[j*QW+M+h*D+d]+=g*b->qkv[i*QW+h*D+d];}break;}case 10:mmback(b->x,b->wq,s->dqkv,b->dx,b->dwq,T,M,QW);break;default:return-1;}return 0;}
static int execute(void*opaque){Context*c=opaque;if(*c->live_generation!=c->generation)return-4;if(c->kind==ZERO_ACTION)return zero_one(c);if(c->kind==REMAT_ACTION){forward(c->b);return 0;}return reverse_one(c);}
static unsigned emit(Block*b,Scratch*s,const float*seed,uint32_t*generation,ExecStep*steps,Context*ctx){unsigned at=0;for(unsigned i=0;i<9;i++){ctx[at]=(Context){b,s,seed,ZERO_ACTION,i,*generation,generation};steps[at]=(ExecStep){execute,&ctx[at],ZERO_ACTION,0,0};at++;}for(unsigned i=0;i<9;i++){ctx[at]=(Context){b,s,seed,REVERSE_ACTION,i,*generation,generation};steps[at]=(ExecStep){execute,&ctx[at],REVERSE_ACTION,0,0};at++;}ctx[at]=(Context){b,s,seed,REMAT_ACTION,0,*generation,generation};steps[at]=(ExecStep){execute,&ctx[at],REMAT_ACTION,0,0};at++;for(unsigned i=9;i<11;i++){ctx[at]=(Context){b,s,seed,REVERSE_ACTION,i,*generation,generation};steps[at]=(ExecStep){execute,&ctx[at],REVERSE_ACTION,0,0};at++;}return at;}
static void initialize(Block*b,float*seed){memset(b,0,sizeof *b);for(int i=0;i<T*M;i++)b->x[i]=initv(i,1),seed[i]=initv(i,6);for(int i=0;i<M*QW;i++)b->wq[i]=initv(i,2)*.4f;for(int i=0;i<M*M;i++)b->wo[i]=initv(i,3)*.4f;for(int i=0;i<M*F;i++)b->w1[i]=initv(i,4)*.5f;for(int i=0;i<F*M;i++)b->w2[i]=initv(i,5)*.5f;forward(b);}
static int same(const float*a,const float*b,unsigned n){for(unsigned i=0;i<n;i++)if(fabsf(a[i]-b[i])>2e-6f*fmaxf(1,fmaxf(fabsf(a[i]),fabsf(b[i]))))return 0;return 1;}
#ifndef TRANSFORMER_EXECUTOR_NO_MAIN
int main(void){Block reference,actual;Scratch scratch={0};float seed[T*M];initialize(&reference,seed);initialize(&actual,seed);backward(&reference,seed);ExecStep steps[21];Context ctx[21];uint32_t generation=12;unsigned count=emit(&actual,&scratch,seed,&generation,steps,ctx);if(count!=21||tensor_transformer_steps_execute(steps,count))return 1;if(!same(reference.dx,actual.dx,T*M)||!same(reference.dwq,actual.dwq,M*QW)||!same(reference.dwo,actual.dwo,M*M)||!same(reference.dw1,actual.dw1,M*F)||!same(reference.dw2,actual.dw2,F*M))return 1;generation++;if(tensor_transformer_steps_execute(steps,count)!=-4)return 1;printf("tensor transformer backward executor passed: actions=21 zero=9 reverse=11 remat=1 gradients=x,wqkv,wo,w1,w2 monolithic_reference=exact lifetime=checked executor=x86_64-assembly\n");return 0;}
#endif
#endif
