#ifndef TENSOR_PLAN_TRACE_ADAPTER_SPIKE_H
#define TENSOR_PLAN_TRACE_ADAPTER_SPIKE_H
#include "tensor_plan_trace_spike.h"
typedef struct {const char*name;uint64_t peak_bytes,compute_cost,actions;uint32_t feasible;} PlannerCandidateOutput;
typedef struct {const char*subject,*constraint,*reason;PlannerCandidateOutput candidate[TRACE_MAX_ALTS];uint32_t count,chosen;uint64_t budget,counterfactual_budget;int32_t counterfactual_choice;MeasurementProvenance provenance;} PlannerDecisionOutput;
static int planner_choose_memory(PlannerDecisionOutput*d,uint64_t budget,uint64_t cf){d->budget=budget;d->counterfactual_budget=cf;d->chosen=UINT32_MAX;d->counterfactual_choice=-1;uint64_t best=UINT64_MAX,cfbest=UINT64_MAX;for(uint32_t i=0;i<d->count;i++){uint64_t cost=(d->candidate[i].peak_bytes>budget?d->candidate[i].peak_bytes-budget:0)+d->candidate[i].compute_cost;if(d->candidate[i].feasible&&cost<best){best=cost;d->chosen=i;}uint64_t cfcost=(d->candidate[i].peak_bytes>cf?d->candidate[i].peak_bytes-cf:0)+d->candidate[i].compute_cost;if(d->candidate[i].feasible&&cfcost<cfbest){cfbest=cfcost;d->counterfactual_choice=(int32_t)i;}}return d->chosen==UINT32_MAX?-1:0;}
static int planner_choose_measured(PlannerDecisionOutput*d,uint32_t verified,uint32_t uncertain){d->chosen=0;if(verified&&!uncertain)for(uint32_t i=1;i<d->count;i++)if(d->candidate[i].feasible&&d->candidate[i].compute_cost<d->candidate[d->chosen].compute_cost)d->chosen=i;return 0;}
static int trace_from_planner(PlanTrace*t,const PlannerDecisionOutput*p){if(t->count==TRACE_MAX_DECISIONS||!p->count||p->count>TRACE_MAX_ALTS||p->chosen>=p->count)return-1;PlanDecisionTrace*d=&t->decisions[t->count++];memset(d,0,sizeof*d);snprintf(d->subject,sizeof d->subject,"%s",p->subject);snprintf(d->constraint,sizeof d->constraint,"%s",p->constraint);snprintf(d->reason,sizeof d->reason,"%s",p->reason);d->alternative_count=p->count;d->chosen=p->chosen;d->budget=p->budget;d->counterfactual_budget=p->counterfactual_budget;d->counterfactual_choice=p->counterfactual_choice;d->provenance=p->provenance;for(uint32_t i=0;i<p->count;i++){snprintf(d->alternatives[i].name,sizeof d->alternatives[i].name,"%s",p->candidate[i].name);d->alternatives[i].peak_bytes=p->candidate[i].peak_bytes;d->alternatives[i].compute_cost=p->candidate[i].compute_cost;d->alternatives[i].actions=p->candidate[i].actions;d->alternatives[i].feasible=p->candidate[i].feasible;}return 0;}
#endif
