/* Real GPT-2 124M generation: differential + property check.
 *
 * Roadmap item 3 ("connect tokenizer, full logits and the already gated
 * sampling contract; verify greedy generation exactly and stochastic
 * generation by deterministic seed replay"). KV-cache is explicitly item 4
 * (not this file) -- every generation step here does a full recompute
 * from scratch via tensor_gpt2_forward.h's runtime-n forward pass, the
 * same "hand-rolled runtime reference" pattern already anchored for the
 * toy KV-cache/autoregressive-loop checks, now with the real weights.
 *
 * Layers of verification:
 *   1. ANCHOR: gpt2_forward_ex's logits at the fixed n=8, fixed-token-id
 *      input this project has already run through the real canonical
 *      compile()+executor (tensor_gpt2_full_differential_check.c) are
 *      compared against that SAME PyTorch reference fixture
 *      (full_logits.f32). Matching it anchors this runtime-n forward pass
 *      to the already-verified canonical/executor path, transitively --
 *      same weights, same math, same external reference.
 *   1b. TOKEN-FOR-TOKEN: real PyTorch greedy generation sequences for 4
 *      prompts (scratchpad/gpt2_block_boundary/greedy_reference.txt,
 *      generated by generate_greedy_reference.py in the same directory)
 *      are compared token by token against this project's own greedy
 *      generation from the same prompts. This is the actual claim "our
 *      greedy generation matches PyTorch's greedy generation", checked
 *      directly -- the anchor above only proves single-step logits
 *      agreement at one fixed n; this proves the generation LOOP itself
 *      (repeated sampling + append) tracks the real model exactly over
 *      12 generated tokens per prompt, including a deliberately
 *      out-of-distribution prompt ([1,2,3,4,5]) where real GPT-2's own
 *      greedy decoding degenerates into a repeating 2-token loop --
 *      reproducing that exact degenerate repetition is itself a
 *      meaningful check, not just "produces plausible text".
 *   2. Greedy generation determinism: same prompt -> identical generated
 *      sequence on repeated runs (trivially true for greedy, checked
 *      anyway as a regression guard).
 *   3. Temperature/top-k generation: deterministic seed replay (same
 *      seed -> identical sequence, using the already-gated
 *      sample_top_k_temperature contract) and prefix-stability (a
 *      shorter generation from the same seed is an exact prefix of a
 *      longer one) -- same properties already proven for the toy
 *      autoregressive loop, now end-to-end on the real model.
 *   4. A real end-to-end demo: encode a real ASCII text prompt with this
 *      project's own BPE tokenizer, greedily generate with the real
 *      model, decode back to text with the same tokenizer. Printed for
 *      inspection; not itself a pass/fail gate (no "good continuation"
 *      oracle exists), but must produce well-formed, decodable token ids.
 */
#include "tensor_gpt2_forward.h"
#include "tensor_gpt2_bpe.h"
#include "tensor_sampling.h"
#include <stdio.h>
#include <stdlib.h>

enum { MAX_GEN = GPT2_MAXT };

static int load_f32(const char *dir, const char *name, float *out, size_t count) {
    char path[512];
    snprintf(path, sizeof path, "%s/%s.f32", dir, name);
    FILE *f = fopen(path, "rb");
    if (!f) return -1;
    size_t got = fread(out, sizeof(float), count, f);
    fclose(f);
    return got == count ? 0 : -1;
}

static Gpt2Weights g_w;
static float g_ref_logits[8 * GPT2_VOCAB];

static int greedy_argmax(const float *logits, int vocab) {
    int best = 0;
    for (int i = 1; i < vocab; i++) if (logits[i] > logits[best]) best = i;
    return best;
}

static int required_mode(void) {
    const char *v = getenv("GPT2_GENERATION_REQUIRED");
    return v && !strcmp(v, "1");
}
static int unavailable(const char *what) {
    fprintf(required_mode() ? stderr : stdout, "gpt2_generation: %s -- %s\n", what, required_mode() ? "required gate failed" : "optional gate skipped");
    return required_mode() ? 1 : 0;
}

/* Reads one line of greedy_reference.txt: "N_PROMPT p1..pN N_GEN g1..gN".
 * Fails closed (returns -1) on any malformed/truncated/out-of-bounds
 * field -- np/ng are validated against the caller's buffer capacity
 * BEFORE being used as loop bounds, so a corrupted fixture can't drive
 * an out-of-bounds write. Returns 1 on a clean EOF (no more cases), 0 on
 * a successfully read case. */
static int read_greedy_case(FILE *f, int *prompt, int prompt_cap, int *np_out, int *gen, int gen_cap, int *ng_out) {
    int np;
    int r = fscanf(f, "%d", &np);
    if (r == EOF) return 1;
    if (r != 1) return -1;
    if (np <= 0 || np > prompt_cap) { fprintf(stderr, "read_greedy_case: prompt length %d out of bounds (cap %d)\n", np, prompt_cap); return -1; }
    for (int i = 0; i < np; i++) if (fscanf(f, "%d", &prompt[i]) != 1) { fprintf(stderr, "read_greedy_case: truncated prompt\n"); return -1; }
    int ng;
    if (fscanf(f, "%d", &ng) != 1) { fprintf(stderr, "read_greedy_case: missing generated-length field\n"); return -1; }
    if (ng < 0 || ng > gen_cap) { fprintf(stderr, "read_greedy_case: generated length %d out of bounds (cap %d)\n", ng, gen_cap); return -1; }
    for (int i = 0; i < ng; i++) if (fscanf(f, "%d", &gen[i]) != 1) { fprintf(stderr, "read_greedy_case: truncated generation\n"); return -1; }
    *np_out = np; *ng_out = ng;
    return 0;
}

int main(int argc, char **argv) {
    const char *fixture_dir = argc > 1 ? argv[1] : "scratchpad/gpt2_block_boundary";
    const char *safetensors_path = argc > 2 ? argv[2] : "/Users/ll/.cache/huggingface/hub/models--gpt2/snapshots/607a30d783dfa663caf39e06633721c8d4cfcd7e/model.safetensors";
    const char *vocab_path = argc > 3 ? argv[3] : "scratchpad/gpt2_tokenizer_fixture/vocab.json";
    const char *merges_path = argc > 4 ? argv[4] : "scratchpad/gpt2_tokenizer_fixture/merges.txt";
    static const char *EXPECT_SHA = "248dfc3911869ec493c76e65bf2fcf7f615828b0254c12b473182f0f81d3a707";

    if (gpt2_load_weights(&g_w, safetensors_path, EXPECT_SHA)) return unavailable("real checkpoint not found/verified");
    if (load_f32(fixture_dir, "full_logits", g_ref_logits, 8 * GPT2_VOCAB)) return unavailable("reference fixture not found");
    static Gpt2Bpe bpe;
    int have_tokenizer = !gpt2_bpe_load(&bpe, vocab_path, merges_path);
    if (!have_tokenizer) { if (unavailable("tokenizer fixture not found")) return 1; }

    /* 1. anchor: same fixed tokens as tensor_gpt2_full_differential_check.c */
    int anchor_tokens[8] = {464, 3290, 3332, 2159, 0, 1, 50256, 464};
    static float anchor_logits[8 * GPT2_VOCAB];
    gpt2_forward_ex(&g_w, anchor_tokens, 8, anchor_logits, 0);
    float max_abs = 0, max_rel = 0;
    int fails = 0;
    for (int i = 0; i < 8 * GPT2_VOCAB; i++) {
        float diff = fabsf(anchor_logits[i] - g_ref_logits[i]);
        float bound = fmaxf(3e-2f, 2e-3f * fabsf(g_ref_logits[i]));
        if (diff > max_abs) max_abs = diff;
        float rel = diff / (fabsf(g_ref_logits[i]) + 1e-8f);
        if (rel > max_rel) max_rel = rel;
        if (diff > bound) fails++;
    }
    printf("anchor: gpt2_forward_ex logits vs PyTorch reference: elements=%d max_abs=%.6g max_rel=%.6g fails=%d\n", 8 * GPT2_VOCAB, max_abs, max_rel, fails);
    if (fails > 0) { fprintf(stderr, "gpt2_generation: anchor FAILED -- runtime-n forward pass diverges from the already-verified canonical path\n"); return 1; }

    /* 1b. token-for-token greedy generation vs real PyTorch greedy
     * sequences, for several prompts (not just a single anchored logits
     * snapshot). This is the actual claim "our greedy generation matches
     * PyTorch's greedy generation", checked directly rather than
     * inferred from one-step logits agreement plus internal
     * self-consistency. */
    {
        char path[512];
        snprintf(path, sizeof path, "%s/greedy_reference.txt", fixture_dir);
        FILE *gf = fopen(path, "rb");
        if (!gf) {
            if (unavailable("greedy_reference.txt not found")) return 1;
        } else {
            int case_no = 0, all_ok = 1;
            int np, ng;
            int ref_prompt[MAX_GEN], ref_gen[MAX_GEN];
            int rc;
            while ((rc = read_greedy_case(gf, ref_prompt, MAX_GEN, &np, ref_gen, MAX_GEN, &ng)) == 0) {
                int seq[MAX_GEN];
                for (int i = 0; i < np; i++) seq[i] = ref_prompt[i];
                for (int step = 0; step < ng && np + step < MAX_GEN; step++) {
                    int n = np + step;
                    static float logits[GPT2_VOCAB];
                    gpt2_forward_ex(&g_w, seq, n, logits, 1);
                    seq[n] = greedy_argmax(logits, GPT2_VOCAB);
                }
                int mism = -1;
                for (int i = 0; i < ng && np + i < MAX_GEN; i++) if (seq[np + i] != ref_gen[i]) { mism = i; break; }
                if (mism >= 0) {
                    fprintf(stderr, "gpt2_generation: case %d token-for-token mismatch at generated position %d: got=%d want=%d\n", case_no, mism, seq[np + mism], ref_gen[mism]);
                    all_ok = 0;
                } else {
                    printf("case %d: %d/%d generated tokens exactly match the real PyTorch greedy sequence (prompt_len=%d)\n", case_no, ng, ng, np);
                }
                case_no++;
            }
            fclose(gf);
            if (rc < 0) { fprintf(stderr, "gpt2_generation: greedy_reference.txt malformed/truncated after %d case(s)\n", case_no); return 1; }
            if (!all_ok) { fprintf(stderr, "gpt2_generation: token-for-token greedy cross-check FAILED\n"); return 1; }
            printf("token-for-token: all %d prompts' full greedy continuations exactly match real PyTorch generation (not just single-step logits)\n", case_no);
        }
    }

    /* 2. greedy generation determinism */
    int prompt[4] = {464, 3290, 3332, 2159};
    int gen_len = 6;
    int seq_a[MAX_GEN], seq_b[MAX_GEN];
    for (int i = 0; i < 4; i++) { seq_a[i] = prompt[i]; seq_b[i] = prompt[i]; }
    for (int step = 0; step < gen_len; step++) {
        int n = 4 + step;
        static float logits[GPT2_VOCAB];
        gpt2_forward_ex(&g_w, seq_a, n, logits, 1);
        seq_a[n] = greedy_argmax(logits, GPT2_VOCAB);
    }
    for (int step = 0; step < gen_len; step++) {
        int n = 4 + step;
        static float logits[GPT2_VOCAB];
        gpt2_forward_ex(&g_w, seq_b, n, logits, 1);
        seq_b[n] = greedy_argmax(logits, GPT2_VOCAB);
    }
    int greedy_mismatch = 0;
    for (int i = 0; i < 4 + gen_len; i++) if (seq_a[i] != seq_b[i]) greedy_mismatch = 1;
    if (greedy_mismatch) { fprintf(stderr, "gpt2_generation: greedy determinism FAILED\n"); return 1; }
    printf("greedy: two independent %d-token generations from the same prompt are byte-identical. tokens:", 4 + gen_len);
    for (int i = 0; i < 4 + gen_len; i++) printf(" %d", seq_a[i]);
    printf("\n");

    /* 3. temperature/top-k: seed-replay determinism + prefix stability */
    {
        SampleRng r1 = {0xC0FFEE}, r2 = {0xC0FFEE};
        int full_len = 6;
        int seqA[MAX_GEN], seqB[MAX_GEN];
        for (int i = 0; i < 4; i++) { seqA[i] = prompt[i]; seqB[i] = prompt[i]; }
        for (int step = 0; step < full_len; step++) {
            int n = 4 + step;
            static float logits[GPT2_VOCAB];
            gpt2_forward_ex(&g_w, seqA, n, logits, 1);
            int next = sample_top_k_temperature(logits, GPT2_VOCAB, 40, 0.8f, &r1);
            if (next < 0) { fprintf(stderr, "sampler rejected valid input\n"); return 1; }
            seqA[n] = next;
        }
        for (int step = 0; step < full_len; step++) {
            int n = 4 + step;
            static float logits[GPT2_VOCAB];
            gpt2_forward_ex(&g_w, seqB, n, logits, 1);
            int next = sample_top_k_temperature(logits, GPT2_VOCAB, 40, 0.8f, &r2);
            if (next < 0) { fprintf(stderr, "sampler rejected valid input\n"); return 1; }
            seqB[n] = next;
        }
        int mismatch = 0;
        for (int i = 0; i < 4 + full_len; i++) if (seqA[i] != seqB[i]) mismatch = 1;
        if (mismatch) { fprintf(stderr, "gpt2_generation: temp/top-k replay determinism FAILED\n"); return 1; }
        printf("temp/top-k replay: same seed reproduces an identical %d-token sequence. tokens:", 4 + full_len);
        for (int i = 0; i < 4 + full_len; i++) printf(" %d", seqA[i]);
        printf("\n");

        SampleRng r3 = {0xC0FFEE};
        int shorter_len = full_len - 2;
        int seqC[MAX_GEN];
        for (int i = 0; i < 4; i++) seqC[i] = prompt[i];
        for (int step = 0; step < shorter_len; step++) {
            int n = 4 + step;
            static float logits[GPT2_VOCAB];
            gpt2_forward_ex(&g_w, seqC, n, logits, 1);
            int next = sample_top_k_temperature(logits, GPT2_VOCAB, 40, 0.8f, &r3);
            if (next < 0) { fprintf(stderr, "sampler rejected valid input\n"); return 1; }
            seqC[n] = next;
        }
        int prefix_mismatch = 0;
        for (int i = 0; i < 4 + shorter_len; i++) if (seqC[i] != seqA[i]) prefix_mismatch = 1;
        if (prefix_mismatch) { fprintf(stderr, "gpt2_generation: prefix-stability FAILED\n"); return 1; }
        printf("prefix stability: a %d-token generation is an exact prefix of the %d-token generation from the same seed\n", 4 + shorter_len, 4 + full_len);
    }

    /* 4. real end-to-end text demo (not a pass/fail gate beyond
     * well-formedness: must encode, generate, and decode without error) */
    if (have_tokenizer) {
        const char *prompt_text = "The quick brown fox";
        int ids[MAX_GEN];
        int prompt_n = gpt2_bpe_encode(&bpe, prompt_text, (int)strlen(prompt_text), ids, MAX_GEN);
        if (prompt_n < 0) { fprintf(stderr, "gpt2_generation: tokenizer encode failed on demo prompt\n"); return 1; }
        int demo_gen = 12;
        if (prompt_n + demo_gen > MAX_GEN) demo_gen = MAX_GEN - prompt_n;
        for (int step = 0; step < demo_gen; step++) {
            int n = prompt_n + step;
            static float logits[GPT2_VOCAB];
            gpt2_forward_ex(&g_w, ids, n, logits, 1);
            ids[n] = greedy_argmax(logits, GPT2_VOCAB);
        }
        char decoded[2048];
        int dn = gpt2_bpe_decode(&bpe, ids, prompt_n + demo_gen, decoded, sizeof decoded - 1);
        if (dn < 0) { fprintf(stderr, "gpt2_generation: tokenizer decode failed on demo output\n"); return 1; }
        decoded[dn] = '\0';
        printf("demo: prompt=%.60s -> greedy continuation (%d new tokens): %s\n", prompt_text, demo_gen, decoded);
    }

    puts("gpt2_generation differential/property check passed: runtime-n forward pass anchored to the canonical/executor path via the real PyTorch reference, greedy generation deterministic, temperature/top-k generation seed-replay deterministic with exact prefix stability, real text prompt encodes/generates/decodes end to end");
    return 0;
}
