#define TRANSFORMER_EXECUTOR_NO_MAIN
#include "tensor_transformer_executor_spike.h"
#undef TRANSFORMER_EXECUTOR_NO_MAIN
#include <math.h>
#include <stdint.h>
#include <stdio.h>
enum{F_QKV,F_VIEW,F_ATTN,F_CONTIG,F_OUT,F_RES1,F_LN1,F_FF1,F_RELU,F_FF2,F_RES2,F_LN2,F_LOSS,F_OPT};
typedef struct{Block*b;uint32_t kind,index,generation,*live;float*target,*seed,*loss,*param,*grad,lr;unsigned count;}TrainContext;
static int train_action(void*opaque){TrainContext*c=opaque;Block*b=c->b;if(*c->live!=c->generation)return-4;switch(c->kind){case F_QKV:mm(b->x,b->wq,b->qkv,T,M,QW);break;case F_VIEW:if(c->index>2)return-1;break;case F_ATTN:{float scale=1/sqrtf(D);for(int h=0;h<H;h++)for(int i=0;i<T;i++){float mx=-INFINITY;for(int j=0;j<T;j++){float s=0;for(int d=0;d<D;d++)s+=b->qkv[i*QW+h*D+d]*b->qkv[j*QW+M+h*D+d];s*=scale;b->score[(h*T+i)*T+j]=s;mx=fmaxf(mx,s);}float total=0;for(int j=0;j<T;j++){float e=expf(b->score[(h*T+i)*T+j]-mx);b->prob[(h*T+i)*T+j]=e;total+=e;}for(int j=0;j<T;j++)b->prob[(h*T+i)*T+j]/=total;for(int d=0;d<D;d++){float s=0;for(int j=0;j<T;j++)s+=b->prob[(h*T+i)*T+j]*b->qkv[j*QW+2*M+h*D+d];b->head[(h*T+i)*D+d]=s;}}break;}case F_CONTIG:for(int i=0;i<T;i++)for(int h=0;h<H;h++)for(int d=0;d<D;d++)b->merge[i*M+h*D+d]=b->head[(h*T+i)*D+d];break;case F_OUT:mm(b->merge,b->wo,b->proj,T,M,M);break;case F_RES1:for(int i=0;i<T*M;i++)b->s1[i]=b->x[i]+b->proj[i];break;case F_LN1:ln(b->s1,b->ln1,b->mean1,b->inv1);break;case F_FF1:mm(b->ln1,b->w1,b->z1,T,M,F);break;case F_RELU:for(int i=0;i<T*F;i++)b->act[i]=b->z1[i]>0?b->z1[i]:0;break;case F_FF2:mm(b->act,b->w2,b->ff,T,F,M);break;case F_RES2:for(int i=0;i<T*M;i++)b->s2[i]=b->ln1[i]+b->ff[i];break;case F_LN2:ln(b->s2,b->out,b->mean2,b->inv2);break;case F_LOSS:*c->loss=0;for(int i=0;i<T*M;i++){float e=b->out[i]-c->target[i];*c->loss+=e*e;c->seed[i]=2*e/(T*M);}*c->loss/=T*M;break;case F_OPT:for(unsigned i=0;i<c->count;i++)c->param[i]-=c->lr*c->grad[i];break;default:return-1;}return 0;}
static unsigned emit_forward(Block*b,uint32_t*generation,ExecStep*s,TrainContext*c){static const uint8_t kinds[]={F_QKV,F_VIEW,F_VIEW,F_VIEW,F_ATTN,F_CONTIG,F_OUT,F_RES1,F_LN1,F_FF1,F_RELU,F_FF2,F_RES2,F_LN2};for(unsigned i=0;i<14;i++){c[i]=(TrainContext){.b=b,.kind=kinds[i],.index=i>0&&i<4?i-1:0,.generation=*generation,.live=generation};s[i]=(ExecStep){train_action,&c[i],kinds[i],0,0};}return 14;}
static void target_make(float*t){for(int i=0;i<T;i++){float m=0,v=0;for(int j=0;j<M;j++){t[i*M+j]=sinf((i+1)*(j+2)*.7f)+cosf((i-j)*.4f);m+=t[i*M+j];}m/=M;for(int j=0;j<M;j++){float d=t[i*M+j]-m;v+=d*d;}float inv=1/sqrtf(v/M+1e-5f);for(int j=0;j<M;j++)t[i*M+j]=(t[i*M+j]-m)*inv;}}
int main(void){Block b;Scratch scratch={0};float seed[T*M],target[T*M],loss=0;initialize(&b,seed);target_make(target);uint32_t generation=41;ExecStep forward_steps[14],backward_steps[21],loss_step,opt[4];TrainContext fc[14],lc={.b=&b,.kind=F_LOSS,.generation=generation,.live=&generation,.target=target,.seed=seed,.loss=&loss},oc[4];Context stable[21];loss_step=(ExecStep){train_action,&lc,F_LOSS,0,0};float initial=0;for(unsigned epoch=0;epoch<12000;epoch++){emit_forward(&b,&generation,forward_steps,fc);if(tensor_transformer_steps_execute(forward_steps,14)||tensor_transformer_steps_execute(&loss_step,1))return 2;if(!epoch)initial=loss;unsigned bc=emit(&b,&scratch,seed,&generation,backward_steps,stable);if(bc!=21||tensor_transformer_steps_execute(backward_steps,bc))return 3;oc[0]=(TrainContext){.b=&b,.kind=F_OPT,.generation=generation,.live=&generation,.param=b.wq,.grad=b.dwq,.lr=.02f,.count=M*QW};oc[1]=(TrainContext){.b=&b,.kind=F_OPT,.generation=generation,.live=&generation,.param=b.wo,.grad=b.dwo,.lr=.02f,.count=M*M};oc[2]=(TrainContext){.b=&b,.kind=F_OPT,.generation=generation,.live=&generation,.param=b.w1,.grad=b.dw1,.lr=.02f,.count=M*F};oc[3]=(TrainContext){.b=&b,.kind=F_OPT,.generation=generation,.live=&generation,.param=b.w2,.grad=b.dw2,.lr=.02f,.count=F*M};for(int i=0;i<4;i++)opt[i]=(ExecStep){train_action,&oc[i],F_OPT,0,0};if(tensor_transformer_steps_execute(opt,4))return 4;}emit_forward(&b,&generation,forward_steps,fc);tensor_transformer_steps_execute(forward_steps,14);tensor_transformer_steps_execute(&loss_step,1);printf("tensor transformer scheduled training passed: forward=14 loss=1 backward=21 optimizer=4 epochs=12000 loss=%.6f->%.6f executor=x86_64-assembly\n",initial,loss);return loss<initial*.01f?0:1;}
