/* tensorctl build: lower the imported ONNX v0 graph to a standalone native
 * executable. The artifact accepts INPUT.f32 and OUTPUT.f32 paths; weights are
 * embedded from ONNX initializers without sidecar files or model-specific code. */
#include "tensor_onnx_import.h"
#include <limits.h>
#include <sys/wait.h>
#include <unistd.h>

static uint64_t build_elems(const int64_t*d,uint32_t n){uint64_t x=1;for(uint32_t i=0;i<n;i++){if(d[i]<=0)return 0;x*=(uint64_t)d[i];}return x;}
static int initializer_index(const OnnxGraph*g,const char*name){for(uint32_t i=0;i<g->n_initializers;i++)if(!strcmp(g->initializers[i].name,name))return(int)i;return-1;}
static int input_index(const OnnxGraph*g,const char*name){for(uint32_t i=0;i<g->n_inputs;i++)if(!strcmp(g->inputs[i].name,name))return(int)i;return-1;}
static int producer_index(const OnnxGraph*g,const char*name){for(uint32_t i=0;i<g->n_nodes;i++)for(uint32_t j=0;j<g->nodes[i].n_outputs;j++)if(!strcmp(g->nodes[i].outputs[j],name))return(int)i;return-1;}
static int deterministic_uuid(const char*path,const uint8_t*model,size_t model_len){uint64_t h1=1469598103934665603ull,h2=1099511628211ull;for(size_t i=0;i<model_len;i++){h1=(h1^model[i])*1099511628211ull;h2=(h2+model[i])*0x9e3779b185ebca87ull;}FILE*f=fopen(path,"r+b");if(!f)return-1;uint32_t header[8];if(fread(header,4,8,f)!=8||header[0]!=0xfeedfacf){fclose(f);return-1;}long at=32;for(uint32_t i=0;i<header[4];i++){uint32_t command[2];if(fseek(f,at,SEEK_SET)||fread(command,4,2,f)!=2||command[1]<8){fclose(f);return-1;}if(command[0]==0x1b){uint8_t uuid[16];memcpy(uuid,&h1,8);memcpy(uuid+8,&h2,8);uuid[6]=(uuid[6]&15)|64;uuid[8]=(uuid[8]&63)|128;if(fseek(f,at+8,SEEK_SET)||fwrite(uuid,1,16,f)!=16||fclose(f))return-1;return 0;}at+=command[1];}fclose(f);return-1;}
static void ref(FILE*f,const OnnxGraph*g,const char*name){int i=initializer_index(g,name);if(i>=0)fprintf(f,"w%d",i);else if(input_index(g,name)>=0)fputs("input",f);else{int p=producer_index(g,name);fprintf(f,"v%d",p);}}
static int emit_source(FILE*f,const OnnxGraph*g){if(g->n_inputs!=1||g->n_outputs!=1){fprintf(stderr,"[unsupported] build requires exactly one graph input and one graph output\n");return-1;}uint64_t input_n=build_elems(g->inputs[0].dims,g->inputs[0].ndim);if(!input_n)return-1;
    fputs("#include <math.h>\n#include <stdint.h>\n#include <stdio.h>\n#include <stdlib.h>\nstatic long bi(long x,const long*od,int on,const long*id,int in){long oi[8]={0},q=x,r=0,m=1;for(int i=on-1;i>=0;i--){oi[i]=q%od[i];q/=od[i];}for(int i=in-1;i>=0;i--){long d=id[i],v=oi[on-in+i];r+=(d==1?0:v)*m;m*=d;}return r;}\n",f);
    for(uint32_t i=0;i<g->n_initializers;i++){const OnnxTensor*t=&g->initializers[i];fprintf(f,"static const float w%u[%llu]={",i,(unsigned long long)t->count);for(uint64_t j=0;j<t->count;j++){float x;memcpy(&x,(const uint8_t*)t->data+j*4,4);fprintf(f,"%s%a",j?",":"",(double)x);}fputs("};\n",f);}
    for(uint32_t i=0;i<g->n_nodes;i++)fprintf(f,"static float v%u[%llu];\n",i,(unsigned long long)build_elems(g->nodes[i].out_dims,g->nodes[i].out_ndim));
    fprintf(f,"int main(int argc,char**argv){if(argc!=3){fprintf(stderr,\"usage: %%s INPUT.f32 OUTPUT.f32\\n\",argv[0]);return 2;}float input[%llu];FILE*in=fopen(argv[1],\"rb\");if(!in||fread(input,4,%llu,in)!=%llu||fgetc(in)!=EOF){fprintf(stderr,\"native model: input must contain exactly %llu float32 values\\n\");return 3;}fclose(in);\n",(unsigned long long)input_n,(unsigned long long)input_n,(unsigned long long)input_n,(unsigned long long)input_n);
    for(uint32_t i=0;i<g->n_nodes;i++){const OnnxNode*n=&g->nodes[i];int64_t da[ONNX_MAX_DIMS],db[ONNX_MAX_DIMS];uint32_t an=0,bn=0;onnx_find_value_shape(g,n->inputs[0],da,&an);if(n->n_inputs>1)onnx_find_value_shape(g,n->inputs[1],db,&bn);
        if(!strcmp(n->op_type,"MatMul")||!strcmp(n->op_type,"Gemm")){int gemm=!strcmp(n->op_type,"Gemm"),ta=gemm&&n->transA,tb=gemm&&n->transB;int64_t rows=ta?da[1]:da[0],inner=ta?da[0]:da[1],cols=tb?db[0]:db[1];fprintf(f,"for(long r=0;r<%lld;r++)for(long c=0;c<%lld;c++){float s=0;for(long k=0;k<%lld;k++)s+=",(long long)rows,(long long)cols,(long long)inner);ref(f,g,n->inputs[0]);fputs("[",f);if(ta)fprintf(f,"k*%lld+r",(long long)rows);else fprintf(f,"r*%lld+k",(long long)inner);fputs("] * ",f);ref(f,g,n->inputs[1]);fputs("[",f);if(tb)fprintf(f,"c*%lld+k",(long long)inner);else fprintf(f,"k*%lld+c",(long long)cols);fprintf(f,"];v%u[r*%lld+c]=%a*s",i,(long long)cols,(double)(gemm?n->alpha:1.f));if(gemm&&n->n_inputs==3){fprintf(f,"+%a*",(double)n->beta);ref(f,g,n->inputs[2]);fputs("[c]",f);}fputs(";}\n",f);
        }else if(!strcmp(n->op_type,"Relu")){uint64_t count=build_elems(n->out_dims,n->out_ndim);fprintf(f,"for(long i=0;i<%llu;i++){float x=",(unsigned long long)count);ref(f,g,n->inputs[0]);fprintf(f,"[i];v%u[i]=x>0?x:0;}\n",i);
        }else if(!strcmp(n->op_type,"Add")){uint64_t count=build_elems(n->out_dims,n->out_ndim);fprintf(f,"{static const long od%u[]={",i);for(uint32_t k=0;k<n->out_ndim;k++)fprintf(f,"%s%lld",k?",":"",(long long)n->out_dims[k]);fprintf(f,"},ad%u[]={",i);for(uint32_t k=0;k<an;k++)fprintf(f,"%s%lld",k?",":"",(long long)da[k]);fprintf(f,"},bd%u[]={",i);for(uint32_t k=0;k<bn;k++)fprintf(f,"%s%lld",k?",":"",(long long)db[k]);fprintf(f,"};for(long i=0;i<%llu;i++)v%u[i]=",(unsigned long long)count,i);ref(f,g,n->inputs[0]);fprintf(f,"[bi(i,od%u,%u,ad%u,%u)]+",i,n->out_ndim,i,an);ref(f,g,n->inputs[1]);fprintf(f,"[bi(i,od%u,%u,bd%u,%u)];}\n",i,n->out_ndim,i,bn);
        }else return-1;
    }
    int out=producer_index(g,g->outputs[0].name);if(out<0)return-1;uint64_t output_n=build_elems(g->outputs[0].dims,g->outputs[0].ndim);fprintf(f,"FILE*out=fopen(argv[2],\"wb\");if(!out||fwrite(v%d,4,%llu,out)!=%llu||fclose(out)){fprintf(stderr,\"native model: output write failed\\n\");return 4;}return 0;}\n",out,(unsigned long long)output_n,(unsigned long long)output_n);return 0;
}

int run_build(int argc,char**argv){if(argc!=4||strcmp(argv[2],"-o")){fprintf(stderr,"usage: tensorctl build MODEL.onnx -o MODEL-NATIVE\n");return 2;}OnnxGraph g;if(onnx_load_file(argv[1],&g))return 3;onnx_validate_storage_and_types(&g);if(!onnx_validate_topology(&g))return 3;onnx_infer_shapes(&g);if(g.n_errors||g.n_unsupported){for(uint32_t i=0;i<g.n_errors;i++)fprintf(stderr,"[error] %s\n",g.errors[i].message);for(uint32_t i=0;i<g.n_unsupported;i++)fprintf(stderr,"[unsupported] %s\n",g.unsupported[i].message);return 4;}char tmp[]="/tmp/tensorctl-native.XXXXXX.c";int fd=mkstemps(tmp,2);if(fd<0)return 3;FILE*f=fdopen(fd,"w");if(!f||emit_source(f,&g)||fclose(f)){unlink(tmp);return 3;}char artifact_tmp[PATH_MAX];if(snprintf(artifact_tmp,sizeof artifact_tmp,"%s.tmp.XXXXXX",argv[3])>=(int)sizeof artifact_tmp){unlink(tmp);return 3;}int artifact_fd=mkstemp(artifact_tmp);if(artifact_fd<0){unlink(tmp);return 3;}close(artifact_fd);unlink(artifact_tmp);pid_t pid=fork();if(pid==0){execlp("clang","clang","-arch","x86_64","-O3",tmp,"-o",artifact_tmp,"-lm",(char*)NULL);_exit(127);}int status=0;if(pid<0||waitpid(pid,&status,0)<0){unlink(tmp);unlink(artifact_tmp);return 3;}unlink(tmp);if(!WIFEXITED(status)||WEXITSTATUS(status)){unlink(artifact_tmp);fprintf(stderr,"tensorctl build: native compiler failed\n");return 3;}if(deterministic_uuid(artifact_tmp,g.file_buf,(size_t)g.file_len)||rename(artifact_tmp,argv[3])){unlink(artifact_tmp);return 3;}printf("[derived] native artifact: %s\n[derived] source: imported ONNX initializers and graph\n[derived] reproducibility: deterministic Mach-O UUID derived from ONNX bytes\n[measured] none (run tensorctl verify)\n",argv[3]);return 0;}
