/* Cross-engine trust gate: deterministic raw float32 input bytes are sent to
 * both the ONNX Runtime oracle and the native artifact, then compared. */
#include "tensor_onnx_import.h"
#include <math.h>
#include <sys/wait.h>
#include <unistd.h>

static uint64_t verify_elems(const int64_t*d,uint32_t n){uint64_t x=1;for(uint32_t i=0;i<n;i++){if(d[i]<=0)return 0;x*=(uint64_t)d[i];}return x;}
static int run_child(char*const argv[]){pid_t p=fork();if(p==0){execvp(argv[0],argv);_exit(127);}int s=0;if(p<0||waitpid(p,&s,0)<0)return-1;return WIFEXITED(s)?WEXITSTATUS(s):-1;}
static int temp_file(char*path,size_t cap,const char*stem){snprintf(path,cap,"/tmp/%s.XXXXXX",stem);return mkstemp(path);}
static uint32_t ordered_bits(float x){uint32_t u;memcpy(&u,&x,4);return(u&0x80000000u)?~u:u|0x80000000u;}
static uint32_t ulp_delta(float a,float b){uint32_t x=ordered_bits(a),y=ordered_bits(b);return x>y?x-y:y-x;}
static uint64_t fingerprint(const void*p,size_t n){const uint8_t*b=p;uint64_t h=1469598103934665603ull;for(size_t i=0;i<n;i++)h=(h^b[i])*1099511628211ull;return h;}
static void print_verify_shape(const int64_t*d,uint32_t n){putchar('[');for(uint32_t i=0;i<n;i++)printf("%s%lld",i?",":"",(long long)d[i]);putchar(']');}
static int verify_initializer_index(const OnnxGraph*g,const char*name){for(uint32_t i=0;i<g->n_initializers;i++)if(!strcmp(g->initializers[i].name,name))return(int)i;return-1;}
/* Same old-IR-convention fix as tensorctl_build.c's real_input_index():
 * g.n_inputs counts initializer-shadowed entries too on ir_version=3-era
 * exports (this project's real mnist-8.onnx fixture included) -- find the
 * one input that is NOT also an initializer. */
static int verify_real_input_index(const OnnxGraph*g){int found=-1;for(uint32_t i=0;i<g->n_inputs;i++){if(verify_initializer_index(g,g->inputs[i].name)>=0)continue;if(found>=0)return-2;found=(int)i;}return found;}

int run_verify(int argc,char**argv){int strict=argc==4&&!strcmp(argv[3],"--strict-bits");if((argc!=3&&!strict)){fprintf(stderr,"usage: tensorctl verify MODEL.onnx MODEL-NATIVE [--strict-bits]\n");return 2;}OnnxGraph g;if(onnx_load_file(argv[1],&g))return 3;int in_idx=verify_real_input_index(&g);if(in_idx<0||g.n_outputs!=1){fprintf(stderr,"tensorctl verify: expected exactly one non-initializer graph input and one graph output\n");return 3;}onnx_validate_storage_and_types(&g);if(!onnx_validate_topology(&g))return 3;onnx_infer_shapes(&g);if(g.n_errors||g.n_unsupported)return 4;uint64_t ni=verify_elems(g.inputs[in_idx].dims,g.inputs[in_idx].ndim),no=verify_elems(g.outputs[0].dims,g.outputs[0].ndim);if(!ni||!no)return 4;
    char input[64],native_out[64],oracle_out[64],script[64];int fi=temp_file(input,sizeof input,"tensorctl-input"),fn=temp_file(native_out,sizeof native_out,"tensorctl-native-output"),fo=temp_file(oracle_out,sizeof oracle_out,"tensorctl-oracle-output"),fs=temp_file(script,sizeof script,"tensorctl-ort");if(fi<0||fn<0||fo<0||fs<0)return 3;close(fn);close(fo);FILE*f=fdopen(fi,"wb");uint32_t rng=0x54454e53u;double input_sum=0;for(uint64_t i=0;i<ni;i++){rng=rng*1664525u+1013904223u;float x=(float)((int32_t)(rng>>8))/8388608.f;fwrite(&x,4,1,f);input_sum+=x;}fclose(f);
    f=fdopen(fs,"w");fputs("import numpy as np, onnxruntime as rt, sys\nm,i,o=sys.argv[1:]\ns=rt.InferenceSession(m,providers=['CPUExecutionProvider'])\nx=np.fromfile(i,dtype='<f4').reshape(s.get_inputs()[0].shape)\ny=s.run(None,{s.get_inputs()[0].name:x})[0].astype('<f4',copy=False)\ny.tofile(o)\n",f);fclose(f);
    char*native_argv[]={argv[2],input,native_out,NULL};int nr=run_child(native_argv);const char*python=getenv("TENSORCTL_PYTHON");if(!python)python="python3";char*python_argv[]={(char*)python,script,argv[1],input,oracle_out,NULL};int pr=run_child(python_argv);if(nr||pr){fprintf(stderr,"tensorctl verify: engine failed (native=%d oracle=%d; set TENSORCTL_PYTHON to an environment with onnxruntime)\n",nr,pr);unlink(input);unlink(native_out);unlink(oracle_out);unlink(script);return 3;}
    FILE*a=fopen(native_out,"rb"),*b=fopen(oracle_out,"rb");float*x=malloc(no*4),*y=malloc(no*4);int bad=!a||!b||!x||!y||fread(x,4,no,a)!=no||fread(y,4,no,b)!=no;int native_extra=a&&fgetc(a)!=EOF,oracle_extra=b&&fgetc(b)!=EOF;if(native_extra||oracle_extra)bad=1;if(a)fclose(a);if(b)fclose(b);if(bad){fprintf(stderr,"tensorctl verify: output dtype/shape/byte-count mismatch\n");free(x);free(y);unlink(input);unlink(native_out);unlink(oracle_out);unlink(script);return 5;}double max_abs=0,max_rel=0;uint32_t max_ulp=0;uint64_t bad_at=0,nan_x=0,nan_y=0,inf_x=0,inf_y=0,bit_mismatch=0;for(uint64_t i=0;i<no;i++){nan_x+=isnan(x[i]);nan_y+=isnan(y[i]);inf_x+=isinf(x[i]);inf_y+=isinf(y[i]);if(!isfinite(x[i])||!isfinite(y[i])){if(!bad)bad_at=i;bad=1;continue;}double d=fabs((double)x[i]-y[i]),scale=fmax(fabs(x[i]),fabs(y[i])),rel=d/fmax(scale,1e-30);uint32_t ulp=ulp_delta(x[i],y[i]);if(d>max_abs)max_abs=d;if(rel>max_rel)max_rel=rel;if(ulp>max_ulp)max_ulp=ulp;if(memcmp(&x[i],&y[i],4))bit_mismatch++;double tol=1e-5+1e-5*scale;if(d>tol&&!bad){bad=1;bad_at=i;}}
    int semantic_bad=bad,strict_bad=semantic_bad||(strict&&bit_mismatch);printf("[model] input: shape=");print_verify_shape(g.inputs[in_idx].dims,g.inputs[in_idx].ndim);printf(" dtype=float32 elements=%llu bytes=%llu checksum=%.9g\n",(unsigned long long)ni,(unsigned long long)ni*4,input_sum);printf("[model] output: shape=");print_verify_shape(g.outputs[0].dims,g.outputs[0].ndim);printf(" dtype=float32 elements=%llu bytes=%llu\n",(unsigned long long)no,(unsigned long long)no*4);printf("[measured] oracle: engine=onnxruntime raw_fingerprint=%016llx nan=%llu inf=%llu\n",(unsigned long long)fingerprint(y,no*4),(unsigned long long)nan_y,(unsigned long long)inf_y);printf("[measured] native: raw_fingerprint=%016llx nan=%llu inf=%llu\n",(unsigned long long)fingerprint(x,no*4),(unsigned long long)nan_x,(unsigned long long)inf_x);printf("[measured] error: max_abs=%.9g max_relative=%.9g max_ulp=%u bit_mismatches=%llu/%llu\n",max_abs,max_rel,max_ulp,(unsigned long long)bit_mismatch,(unsigned long long)no);printf("[measured] semantic_verify: %s abs_tol=1e-5 rel_tol=1e-5%s",semantic_bad?"FAIL":"PASS",semantic_bad?" first_bad_index=":"");if(semantic_bad)printf("%llu",(unsigned long long)bad_at);putchar('\n');if(strict)printf("[measured] bitwise_verify: %s\n",strict_bad?"FAIL":"PASS");free(x);free(y);unlink(input);unlink(native_out);unlink(oracle_out);unlink(script);return strict_bad?5:0;}
