#!/usr/bin/env python3
"""Convert selected ELF64 images into Mach-O64 files.

The executable path wraps low-address ELF64 PT_LOAD payloads into a static
Mach-O executable. The object path converts simple ELF64 relocatable objects
generated by fasm into Mach-O objects that clang can link into dylibs.
"""

from __future__ import annotations

import argparse
import stat
import struct
from pathlib import Path

PAGE = 0x1000
MH_MAGIC_64 = 0xFEEDFACF
CPU_TYPE_X86_64 = 0x01000007
CPU_SUBTYPE_X86_64_ALL = 3
MH_EXECUTE = 2
MH_OBJECT = 1
MH_NOUNDEFS = 1
MH_SUBSECTIONS_VIA_SYMBOLS = 0x2000
LC_SEGMENT_64 = 0x19
LC_SYMTAB = 0x2
LC_UNIXTHREAD = 0x5
LC_BUILD_VERSION = 0x32
X86_THREAD_STATE64 = 4
X86_THREAD_STATE64_COUNT = 42
VM_PROT_READ = 1
VM_PROT_WRITE = 2
VM_PROT_EXECUTE = 4
PT_LOAD = 1
ET_REL = 1
ET_EXEC = 2
SHT_PROGBITS = 1
SHT_SYMTAB = 2
SHT_STRTAB = 3
SHT_NOBITS = 8
SHF_WRITE = 1
SHF_ALLOC = 2
SHF_EXECINSTR = 4
N_EXT = 0x01
N_SECT = 0x0E
NO_SECT = 0
S_REGULAR = 0x0
S_ZEROFILL = 0x1
S_ATTR_PURE_INSTRUCTIONS = 0x80000000
S_ATTR_SOME_INSTRUCTIONS = 0x00000400
PLATFORM_MACOS = 1
MACOS_11_0_0 = 0x000B0000


def align(value: int, boundary: int = PAGE) -> int:
    return (value + boundary - 1) & ~(boundary - 1)


def cstr16(name: str) -> bytes:
    raw = name.encode("ascii")
    if len(raw) > 16:
        raise ValueError(f"segment name too long: {name}")
    return raw.ljust(16, b"\0")


def require_elf64(path: Path) -> tuple[bytes, tuple]:
    data = path.read_bytes()
    if len(data) < 64 or data[:4] != b"\x7fELF":
        raise ValueError(f"{path} is not an ELF file")
    if data[4] != 2 or data[5] != 1:
        raise ValueError("expected little-endian ELF64")
    header = struct.unpack_from("<16sHHIQQQIHHHHHH", data, 0)
    if header[2] != 0x3E:
        raise ValueError(f"expected x86_64 ELF machine, got {header[2]:#x}")
    return data, header


def parse_elf64_executable(path: Path) -> tuple[int, list[dict[str, int]], bytes]:
    data, header = require_elf64(path)
    (
        _ident,
        etype,
        machine,
        _version,
        entry,
        phoff,
        _shoff,
        _flags,
        _ehsize,
        phentsize,
        phnum,
        *_rest,
    ) = header
    if etype != ET_EXEC:
        raise ValueError(f"expected ELF executable, got type {etype}")
    if phentsize != 56:
        raise ValueError(f"unexpected ELF64 program header size: {phentsize}")

    loads: list[dict[str, int]] = []
    for index in range(phnum):
        off = phoff + index * phentsize
        p_type, p_flags, p_offset, p_vaddr, _p_paddr, p_filesz, p_memsz, p_align = struct.unpack_from(
            "<IIQQQQQQ", data, off
        )
        if p_type != PT_LOAD:
            continue
        if p_filesz > p_memsz:
            raise ValueError("PT_LOAD has filesz > memsz")
        if p_offset + p_filesz > len(data):
            raise ValueError("PT_LOAD extends past EOF")
        loads.append(
            {
                "flags": p_flags,
                "offset": p_offset,
                "vaddr": p_vaddr,
                "filesz": p_filesz,
                "memsz": p_memsz,
                "align": p_align,
            }
        )

    if not loads:
        raise ValueError("ELF contains no PT_LOAD segments")
    return entry, loads, data


def prot_from_elf(flags: int) -> int:
    prot = 0
    if flags & 4:
        prot |= VM_PROT_READ
    if flags & 2:
        prot |= VM_PROT_WRITE
    if flags & 1:
        prot |= VM_PROT_EXECUTE
    return prot


def segment_command(name: str, vmaddr: int, vmsize: int, fileoff: int, filesize: int, prot: int) -> bytes:
    return struct.pack(
        "<II16sQQQQIIII",
        LC_SEGMENT_64,
        72,
        cstr16(name),
        vmaddr,
        align(vmsize),
        fileoff,
        filesize,
        prot,
        prot,
        0,
        0,
    )


def unixthread_command(entry: int) -> bytes:
    state = [0] * 21
    state[16] = entry
    state[17] = 0x200
    return struct.pack("<IIII", LC_UNIXTHREAD, 184, X86_THREAD_STATE64, X86_THREAD_STATE64_COUNT) + struct.pack(
        "<21Q", *state
    )


def build_version_command() -> bytes:
    return struct.pack("<IIIIII", LC_BUILD_VERSION, 24, PLATFORM_MACOS, MACOS_11_0_0, MACOS_11_0_0, 0)


def build_macho(entry: int, loads: list[dict[str, int]], elf_data: bytes) -> bytes:
    commands: list[bytes] = [
        segment_command("__PAGEZERO", 0, PAGE, 0, 0, 0),
        segment_command("__TEXT", PAGE, PAGE, 0, PAGE, VM_PROT_READ | VM_PROT_EXECUTE),
    ]

    file_cursor = PAGE
    payloads: list[tuple[int, bytes]] = []
    for index, load in enumerate(loads):
        file_cursor = align(file_cursor)
        page_vaddr = load["vaddr"] & ~(PAGE - 1)
        page_delta = load["vaddr"] - page_vaddr
        payload = (b"\0" * page_delta) + elf_data[load["offset"] : load["offset"] + load["filesz"]]
        prot = prot_from_elf(load["flags"])
        commands.append(
            segment_command(
                f"__FASM{index}",
                page_vaddr,
                page_delta + load["memsz"],
                file_cursor,
                len(payload),
                prot,
            )
        )
        payloads.append((file_cursor, payload))
        file_cursor += len(payload)

    commands.append(build_version_command())
    commands.append(unixthread_command(entry))
    sizeofcmds = sum(len(command) for command in commands)
    header = struct.pack(
        "<IiiIIII",
        MH_MAGIC_64,
        CPU_TYPE_X86_64,
        CPU_SUBTYPE_X86_64_ALL,
        MH_EXECUTE,
        len(commands),
        sizeofcmds,
        MH_NOUNDEFS,
    ) + struct.pack("<I", 0)

    if len(header) + sizeofcmds > PAGE:
        raise ValueError("Mach-O load commands do not fit in the reserved header page")

    output = bytearray(PAGE)
    output[: len(header)] = header
    pos = len(header)
    for command in commands:
        output[pos : pos + len(command)] = command
        pos += len(command)

    for fileoff, payload in payloads:
        if len(output) < fileoff:
            output.extend(b"\0" * (fileoff - len(output)))
        output[fileoff : fileoff + len(payload)] = payload

    return bytes(output)


def read_c_string(data: bytes, offset: int) -> str:
    end = data.find(b"\0", offset)
    if end < 0:
        end = len(data)
    return data[offset:end].decode("utf-8", "replace")


def macho_section_name(elf_name: str, flags: int, shtype: int) -> tuple[str, str, int]:
    if flags & SHF_EXECINSTR:
        return "__text", "__TEXT", S_REGULAR | S_ATTR_PURE_INSTRUCTIONS | S_ATTR_SOME_INSTRUCTIONS
    if shtype == SHT_NOBITS:
        return "__bss", "__DATA", S_ZEROFILL
    if flags & SHF_WRITE:
        return "__data", "__DATA", S_REGULAR
    if elf_name in {".rodata", ".rdata"}:
        return "__const", "__TEXT", S_REGULAR
    return "__data", "__DATA", S_REGULAR


def parse_elf64_object(path: Path) -> tuple[list[dict], list[dict], bytes]:
    data, header = require_elf64(path)
    (
        _ident,
        etype,
        _machine,
        _version,
        _entry,
        _phoff,
        shoff,
        _flags,
        _ehsize,
        _phentsize,
        _phnum,
        shentsize,
        shnum,
        shstrndx,
    ) = header
    if etype != ET_REL:
        raise ValueError(f"expected ELF relocatable object, got type {etype}")
    if shentsize != 64:
        raise ValueError(f"unexpected ELF64 section header size: {shentsize}")

    raw_sections = [struct.unpack_from("<IIQQQQIIQQ", data, shoff + i * shentsize) for i in range(shnum)]
    shstr = raw_sections[shstrndx]
    shstr_data = data[shstr[4] : shstr[4] + shstr[5]]

    elf_to_macho: dict[int, int] = {}
    sections: list[dict] = []
    for index, section in enumerate(raw_sections):
        name_off, shtype, flags, addr, offset, size, link, info, addralign, entsize = section
        name = read_c_string(shstr_data, name_off)
        if not (flags & SHF_ALLOC):
            continue
        if shtype not in {SHT_PROGBITS, SHT_NOBITS}:
            continue
        sectname, segname, macho_flags = macho_section_name(name, flags, shtype)
        content = b"" if shtype == SHT_NOBITS else data[offset : offset + size]
        elf_to_macho[index] = len(sections) + 1
        sections.append(
            {
                "elf_index": index,
                "elf_name": name,
                "sectname": sectname,
                "segname": segname,
                "flags": macho_flags,
                "align": addralign.bit_length() - 1 if addralign > 1 else 0,
                "size": size,
                "content": content,
                "addr": 0,
                "offset": 0,
            }
        )

    if not sections:
        raise ValueError("ELF object contains no allocatable sections")

    for section in raw_sections:
        shtype = section[1]
        if shtype in {4, 9}:  # SHT_RELA or SHT_REL
            size = section[5]
            if size:
                raise ValueError("ELF relocations are not supported by the Mach-O object converter yet")

    symbols: list[dict] = []
    for section in raw_sections:
        if section[1] != SHT_SYMTAB:
            continue
        offset, size, link, entsize = section[4], section[5], section[6], section[9]
        if entsize != 24:
            raise ValueError(f"unexpected ELF64 symbol size: {entsize}")
        strtab = raw_sections[link]
        strdata = data[strtab[4] : strtab[4] + strtab[5]]
        count = size // entsize
        for i in range(count):
            st_name, st_info, st_other, st_shndx, st_value, st_size = struct.unpack_from(
                "<IBBHQQ", data, offset + i * entsize
            )
            if st_name == 0 or st_shndx == 0 or st_shndx not in elf_to_macho:
                continue
            bind = st_info >> 4
            typ = st_info & 0xF
            name = read_c_string(strdata, st_name)
            if not name or name.startswith("."):
                continue
            external = bind != 0
            # clang expects C ABI symbols with a leading underscore on Mach-O.
            macho_name = "_" + name
            symbols.append(
                {
                    "name": macho_name,
                    "type": N_SECT | (N_EXT if external else 0),
                    "sect": elf_to_macho[st_shndx],
                    "desc": 0,
                    "value": st_value,
                    "external": external,
                }
            )

    symbols.sort(key=lambda item: (0 if not item["external"] else 1, item["name"]))
    return sections, symbols, data


def build_macho_object(sections: list[dict], symbols: list[dict]) -> bytes:
    header_size = 32
    segment_size = 72 + 80 * len(sections)
    symtab_size = 24
    build_version_size = 24
    sizeofcmds = segment_size + symtab_size + build_version_size
    content_start = align(header_size + sizeofcmds, 8)

    cursor = content_start
    section_payloads: list[tuple[int, bytes]] = []
    addr_cursor = 0
    for section in sections:
        alignment = 1 << section["align"]
        if alignment > 1:
            cursor = align(cursor, alignment)
            addr_cursor = align(addr_cursor, alignment)
        section["offset"] = 0 if section["flags"] & S_ZEROFILL else cursor
        section["addr"] = addr_cursor
        if not section["flags"] & S_ZEROFILL:
            section_payloads.append((cursor, section["content"]))
            cursor += len(section["content"])
        addr_cursor += section["size"]

    symoff = align(cursor, 8)
    stroff = symoff + 16 * len(symbols)
    string_table = bytearray(b"\0")
    nlists = bytearray()
    for symbol in symbols:
        strx = len(string_table)
        string_table.extend(symbol["name"].encode("utf-8") + b"\0")
        nlists.extend(
            struct.pack(
                "<IBBHQ",
                strx,
                symbol["type"],
                symbol["sect"],
                symbol["desc"],
                symbol["value"],
            )
        )

    commands = bytearray()
    commands.extend(
        struct.pack(
            "<II16sQQQQIIII",
            LC_SEGMENT_64,
            segment_size,
            cstr16(""),
            0,
            addr_cursor,
            0,
            cursor,
            VM_PROT_READ | VM_PROT_WRITE | VM_PROT_EXECUTE,
            VM_PROT_READ | VM_PROT_WRITE | VM_PROT_EXECUTE,
            len(sections),
            0,
        )
    )
    for section in sections:
        commands.extend(
            struct.pack(
                "<16s16sQQIIIIIIII",
                cstr16(section["sectname"]),
                cstr16(section["segname"]),
                section["addr"],
                section["size"],
                section["offset"],
                section["align"],
                0,
                0,
                section["flags"],
                0,
                0,
                0,
            )
        )
    commands.extend(struct.pack("<IIIIII", LC_SYMTAB, symtab_size, symoff, len(symbols), stroff, len(string_table)))
    commands.extend(build_version_command())

    output = bytearray()
    output.extend(
        struct.pack(
            "<IiiIIII",
            MH_MAGIC_64,
            CPU_TYPE_X86_64,
            CPU_SUBTYPE_X86_64_ALL,
            MH_OBJECT,
            3,
            sizeofcmds,
            MH_SUBSECTIONS_VIA_SYMBOLS,
        )
    )
    output.extend(struct.pack("<I", 0))
    output.extend(commands)
    if len(output) < content_start:
        output.extend(b"\0" * (content_start - len(output)))
    for offset, content in section_payloads:
        if len(output) < offset:
            output.extend(b"\0" * (offset - len(output)))
        output[offset : offset + len(content)] = content
    if len(output) < symoff:
        output.extend(b"\0" * (symoff - len(output)))
    output[symoff : symoff + len(nlists)] = nlists
    output[stroff : stroff + len(string_table)] = string_table
    return bytes(output)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--type", choices=["exec", "object"], default="exec")
    parser.add_argument("elf", type=Path)
    parser.add_argument("macho", type=Path)
    args = parser.parse_args()

    if args.type == "exec":
        entry, loads, elf_data = parse_elf64_executable(args.elf)
        macho = build_macho(entry, loads, elf_data)
    else:
        sections, symbols, _elf_data = parse_elf64_object(args.elf)
        macho = build_macho_object(sections, symbols)
    args.macho.write_bytes(macho)
    if args.type == "exec":
        mode = args.macho.stat().st_mode
        args.macho.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


if __name__ == "__main__":
    main()
