#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$(mktemp "${TMPDIR:-/tmp}/core-contracts.XXXXXX")"
trap 'rm -f "$OUT"' EXIT

FILES=(
  "fasm/core/file.inc"
  "fasm/core/process.inc"
  "fasm/core/repl.inc"
  "fasm/core/str.inc"
)

{
  cat <<'HEADER'
# Core Contracts

Generated by `scripts/check_core_contracts.sh` from contract comments in selected `fasm/core/*.inc` files.

Each public routine in the checked files must have adjacent `; contract:`, `; returns:`, and `; clobbers:` comments.

HEADER

  missing=0
  for rel in "${FILES[@]}"; do
    file="$ROOT/$rel"
    printf '## `%s`\n\n' "$rel"
    awk -v rel="$rel" '
      function trim(s) {
        sub(/^[[:space:]]+/, "", s)
        sub(/[[:space:]]+$/, "", s)
        return s
      }
      function strip_comment(s) {
        sub(/^[[:space:]]*;[[:space:]]?/, "", s)
        return s
      }
      function reset_comments() {
        count = 0
        delete comments
      }
      /^[[:space:]]*;/ {
        comments[++count] = $0
        next
      }
      /^[A-Za-z_][A-Za-z0-9_]*:$/ {
        name = $0
        sub(/:$/, "", name)
        contract = returns = clobbers = notes = ""
        for (i = 1; i <= count; i++) {
          line = strip_comment(comments[i])
          if (line ~ /^contract:/) {
            contract = trim(substr(line, length("contract:") + 1))
          } else if (line ~ /^returns:/) {
            returns = trim(substr(line, length("returns:") + 1))
          } else if (line ~ /^clobbers:/) {
            clobbers = trim(substr(line, length("clobbers:") + 1))
          } else if (line ~ /^notes:/) {
            notes = trim(substr(line, length("notes:") + 1))
          }
        }
        if (contract == "" || returns == "" || clobbers == "") {
          printf("missing contract metadata: %s:%s\n", rel, name) > "/dev/stderr"
          missing = 1
        }
        printf "### `%s`\n\n", name
        printf "- contract: %s\n", contract
        printf "- returns: %s\n", returns
        printf "- clobbers: %s\n", clobbers
        if (notes != "") {
          printf "- notes: %s\n", notes
        }
        printf "\n"
        reset_comments()
        next
      }
      /^[[:space:]]*$/ {
        next
      }
      {
        reset_comments()
      }
      END {
        if (missing) {
          exit 2
        }
      }
    ' "$file"
  done
} > "$OUT"

perl -0pi -e 's/\n+\z/\n/' "$OUT"

if [[ ! -f "$ROOT/docs/core_contracts.md" ]]; then
  echo "missing docs/core_contracts.md; create it from generated output" >&2
  cat "$OUT" >&2
  exit 1
fi

if ! diff -u "$ROOT/docs/core_contracts.md" "$OUT"; then
  echo "core contract docs are stale; refresh docs/core_contracts.md" >&2
  exit 1
fi

echo "core contract checks passed"
